### ISSUE TITLE
ImportError: cannot import name 'Locale' from 'mimesis.locales'

### ISSUE THREAD

**Issue by cryocaustik** [lk-geimfari/mimesis#1087]
# Bug report

## What's wrong

Attempting to import `from mimesis.locales import Locale` results in error

```python
>>> from mimesis.locales import Locale
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    from mimesis.locales import Locale
ImportError: cannot import name 'Locale' from 'mimesis.locales' (C:\dev\data-generator\.venv\lib\site-packages\mimesis\locales.py)
```

## How is that should be

Locale should import without error

## System information

OS: Win10 Pro v21H1
Python: 3.9.1 64bit
Mimesis: 4.1.3

**Comment by cryocaustik** [comment]
Sorry, just realized that docs default to mimesis v5.0.0 while pypi installs v4.1.3. 

Closing as this is a result of using a v5 feature in v4

**Comment by lk-geimfari** [comment]
It's my bad that I did not release 5.0.0 yet. I'm going to release it this weekend, I hope. Thank you!

**Comment by lk-geimfari** [comment]
It's my bad that I did not release 5.0.0 yet. I'm going to release it this weekend, I hope. Thank you!
