### ISSUE TITLE
Missing API docs

### ISSUE THREAD

**Issue by zerocewl** [lk-geimfari/mimesis#1098]
# Bug report

The [API](https://mimesis.readthedocs.io/api.html#enums) docs seem to miss most of the content e.g. our sphinx job throws now an error

Warning, treated as error:
```
~/projects/core/core/generators.py:docstring of publiqa.generators.first_name::py:class reference target not found: mimesis.enums.Gender
```

**Comment by lk-geimfari** [comment]
I've fixed this issue.

**Comment by zerocewl** [comment]
thx, for the quick response.
