### ISSUE TITLE
Include Payment Method in Documents

### ISSUE THREAD

**Issue by kvrameshreddy** [lk-geimfari/mimesis#1111]
Mimesis has Payment method which is not updated in docs. 

can you take a look into this and add the method to docs.

Thankyou

**Comment by lk-geimfari** [comment]
@kvrameshreddy Извините, я не уверен, что понимаю, о чем вы говорите. Не могли бы вы рассказать поподробнее?

**Comment by lk-geimfari** [comment]
@kvrameshreddy Sorry, I'm not sure that I understand what are you talking about. Can you, please, give me more details?

**Comment by lk-geimfari** [comment]
Oh, now I see what are you talking about. I've added [`Payment`](https://mimesis.name/api.html#payment) to [`API Reference`](https://mimesis.name/api.html). Thank you very much!
