### ISSUE TITLE
US locale-based addresses include non-US street suffixes

### ISSUE THREAD

**Issue by willsthompson** [lk-geimfari/mimesis#1247]
# Bug report

## What's wrong

When creating addresses using a provider based on the US locale, e.g.
```python
en = mimesis.Address(locale=Locale.EN)
en.address()
```
addresses are returned including street suffixes that are not valid in the US, such as
```
'Bay', 'Brae', 'Close', 'Drung', 'Esplanade', 'Gate', 'Line', 'Nene', 'Parade', 'Plantation', 'Private', 'Promenade', 'Sideline', 'Townline', 'Wynd'
```

## How is that should be

Output should only include only valid street suffixes as defined by USPS: https://pe.usps.com/text/pub28/28apc_002.htm

**Comment by willsthompson** [comment]
This looks like a straightforward fix by removing the invalid values and/or replacing them with valid ones in the US locale's `address.json` file. If you have any suggestions on how you'd like it handle, I'd be happy to submit a PR.

**Comment by lk-geimfari** [comment]
Hi! Thank you for your interest. I'll wait for your PR. Thank you!
