### ISSUE TITLE
Address provider function country() does not apply locale or support allow_random param

### ISSUE THREAD

**Issue by willsthompson** [lk-geimfari/mimesis#1248]
# Bug report

## What's wrong

The [API documentation](https://mimesis.name/en/master/api.html#mimesis.Address.country) for `Address.country()` indicates that it will "Get the country of the current locale", but the current local is not applied, and it instead always returns a random country:

```
>>> en = mimesis.Address(locale=Locale.EN)
>>> en.country()
'Nicaragua'
>>> en.country()
'Venezuela'
>>> en.country()
'Fiji'
```

Additionally, the function docs include the parameter `allow_random`. However, this has not been implemented:

```python

>>> en.country(allow_random=False)
Traceback (most recent call last):
  File "/Users/willthompson/.pyenv/versions/3.9.11/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: country() got an unexpected keyword argument 'allow_random'
```

## How is that should be

Behavior should align with the documentation:
- Locale should always be applied by default
- Function should accept an `allow_random` parameter that ignores the locale when set to `False`

It looks like this was already implemented in #1114, but closed before merging. Could that be reopened and fixed up?

**Comment by lk-geimfari** [comment]
Absolutely. Can you, please, create a PR?

**Comment by willsthompson** [comment]
@lk-geimfari Sure, I'm happy to do it, but it would essentially be duplicating #1114. Would you rather reopen that one?
