### ISSUE TITLE
Reset increment

### ISSUE THREAD

**Issue by rgoubet** [lk-geimfari/mimesis#1263]
# Feature request

Unless I missed it, there doesn't seem to be a way to reset increments: if you generate data several times with the same schema, increments will pick up from the previous creation:

```python
from mimesis import Field, Schema

_ = Field()
schema = Schema(schema=lambda: {
    "id": _('increment'),
    'name': _('full_name')})

for i in range(0,5):
    data = schema.create(5)
    print(data[0]['id'])
```

This returns:

```
1
6
11
16
21
```

## Thesis

There should be an option to reset the increment each time data is generated.

## Reasoning

When creating large amounts of data to export several times, you don't necessarily want increments to become huge.

**Comment by lk-geimfari** [comment]
Hi! Actually, there is an `accumulator` argument for such cases: https://mimesis.name/en/master/api.html#mimesis.Numeric.increment

Here is a usage example:

```
>>> numeric.increment()
1

>>> numeric.increment(accumulator="a")
1

>>> numeric.increment()
2

numeric.increment(accumulator="a")
2

>>> numeric.increment(accumulator="b")
1

>>> numeric.increment(accumulator="a")
3
```

**Comment by lk-geimfari** [comment]
In your case, you are using schemas wrong way. You don't need this:

```
for i in range(0,5):
    data = schema.create(5)
    print(data[0]['id'])
```

Instead use it like this:

```
for i in schema.create(5):
    print(i['id'])
```

**Comment by lk-geimfari** [comment]
@rgoubet Sorry, I don't get the idea. Can you, please, illustrate it on example?

**Comment by rgoubet** [comment]
My use case is that I want to create multiple, large random data sets in Excel files (generated with openpxl) for stress test purposes. So, let's say I want to create 5 files with 1 million rows each (I use 4 columns for readability, while in practice I get 30):

```python
from mimesis import Field, Schema
from openpyxl import Workbook

_ = Field()

schema = Schema(schema=lambda: {
    "id": _('increment'),
    "timestamp": _('datetime'),
    'version': _('version'),
    'e-mail': _('person.email', domains=['argenx.com']),
    'token': _('token_hex'),
}
```

Now, I'll run a loop for each file, and use the `iterator` to preserve memory:

```python
for i in range(0,5):
    wb = Workbook(write_only=True)
    ws = wb.create_sheet()
    for ix, v in enumerate(schema.iterator(1_000_000)):
        if ix==0:
            ws.append(list(v.keys())) # write headers
        else:
            ws.append(list(v.values())) # write data
    xl_file = os.path.join(path, f'data{str(i).zfill(3)}.xlsx')
    wb.save(xl_file)
    wb.close()
```

Now, it's all good, except that the `id` column increment continues in each file instead of restarting from 1. In my case, that could have been an issue as it can then become a larger number than I would want for the data type I want (turned out ok in the end).

As I said, maybe I missed something, but it would be nice to have a reset option (e.g. in the `create` and `iterator` methods) for the increments. Not critical at all, though.
