### ISSUE TITLE
Mistype in person name

### ISSUE THREAD

**Issue by RomanMerkushin** [lk-geimfari/mimesis#1295]
https://github.com/lk-geimfari/mimesis/blob/7cbde1699e4478840b51263a06f145c7cc996c45/mimesis/data/ru/person.json#L4305

"Магдалена" has an ASCII symbol in last "е" character.

In master:
```shell
>>> [ord(c) for c in "Магдалeна"]
[1052, 1072, 1075, 1076, 1072, 1083, 101, 1085, 1072]
```
Correct name:
```shell
>>> [ord(c) for c in "Магдалена"]
[1052, 1072, 1075, 1076, 1072, 1083, 1077, 1085, 1072]
```

**Comment by lk-geimfari** [comment]
Wow, that's pretty strange. Can you please, create a PR?

**Comment by RomanMerkushin** [comment]
Done
