### ISSUE TITLE
Use of underscore in examples

### ISSUE THREAD

**Issue by Iain-S** [lk-geimfari/mimesis#1301]
# Bug report

## What's wrong?

In the examples [here](https://mimesis.name/en/master/getting_started.html?highlight=_%20%3D%20field#exporting-data) and [here](https://mimesis.name/en/master/getting_started.html?highlight=_%20%3D%20field#exporting-data), you use `_` as a variable name.
For example, 

```python
_ = Field(locale=Locale.EN)
...
```

but sometimes you use

```python
field = Field(Locale.DE)
```

## How should it be?

I think that `_` should be reserved for variables that aren't used, as with

```python
mylist = []
for _ in range(10):
  mylist.append(randint(0,10))
```

and [other common uses](https://stackoverflow.com/a/5893946).
Unless, that is, `_` is used in some important syntactic way (i.e. does it change the behaviour if the variable is not called `_`?).

## System information

N/A

**Comment by lk-geimfari** [comment]
It's just an example. Also, many Django users use it too for `gettext`/`gettext_lazy`.
