### ISSUE TITLE
NSFW words generated by `Text.words` in `en`

### ISSUE THREAD

**Issue by mhauru** [lk-geimfari/mimesis#1320]
The English `text.json` file (https://github.com/lk-geimfari/mimesis/blob/master/mimesis/data/en/text.json) has some words in the `"normal"` section that should probably be in the `"bad"` section. Some candidates for moving to `"bad"` that I spotted while browsing the list: "cock", "cocks", "pussy", "blowjob", "blowjobs", "booty", "busty", "butt". I only quickly browsed the file, that list is probably very incomplete.

There are also words that are in both `"bad"` and `"normal"`, although I'm not quite sure why some of them are in `"bad"`, e.g. "camel".

I haven't checked any of the other localisations, other than `en`.

**Comment by lk-geimfari** [comment]
This is pretty bad. Can you please create PR with fixes?

**Comment by jordiortegon** [comment]
Can confirm that there are some `"bad"` words under the `"normal"` category in Spanish too.
