### ISSUE TITLE
Wrong translation in Swedish

### ISSUE THREAD

**Issue by PierreMesure** [lk-geimfari/mimesis#1404]
Hi,

I just noticed an incorrect translation in Swedish and I wonder how I could fix it. Do you accept a PR or should I change it somewhere else (a translation platform like Crowdin)?

In Swedish, "man" is "man" and "woman" is "kvinna". [Here](https://github.com/lk-geimfari/mimesis/blob/6e6c7235e77337cf5330ac15b786175c3680db2c/mimesis/data/sv/person.json#L10), "man" was translated as "manlig" which means "manly". For "feminine", it would be "kvinnlig".

If the intention was to write "male" and "female", I would simply use "man" and "kvinna".

**Comment by lk-geimfari** [comment]
Hi. It would be great if you could check the data for Swedish.

See https://github.com/lk-geimfari/mimesis/tree/master/mimesis/data/sv.
