### ISSUE TITLE
finance.company() presented inconsistently

### ISSUE THREAD

**Issue by lunik1** [lk-geimfari/mimesis#1408]
# Bug report

## What's wrong

The names of companies are not presented consistently within and between locales. Within locales some company names include the suffix (e.g. Ltd., Corp, etc.)  while others do not, and between locales:
- EN has capitalised company names
- EN_GB names have the stock ticker in brackets at the end
- EN_AU are in ALL CAPS

Most other locales seem to adhere to EN's stile, but I have not checked all.

## How is that should be

Company name formatting should be consistent. I think without suffix would be most useful.

## System information

System-idependent

**Comment by lk-geimfari** [comment]
Hello! You're right. This must be fixed. I'll be happy to merge PR if you want to work on it.
