### ISSUE TITLE
Translate documentation into Russian.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#1427]
- [ ] Add Russian version of the README
- [ ] Add Russian version of the documentation

**Comment by Danko-C** [comment]
Hello! I want to help you and ready to translate both of docs in Russian lang-e. But to be honest I've never translated IT-docs.
Do you have any styleguides? I think, I read all information in "Code", but didn't find anything about text styleguides (I found requrement to code - PIP8). I just find you comment about Crimson Pro font. I apologize if I've been inattentive.

**Comment by lk-geimfari** [comment]
Hi! Thanks for your interest, but I'm already working on this issue myself. Thanks again!

**Comment by Danko-C** [comment]
OK! Thank you for your answer!
