### ISSUE TITLE
Add Arabic language support

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#1435]
Arabic is one of the most widely spoken languages, with a total of 362 million speakers, so it might be a good idea to support it in Mimesis.

There is a list of countries to support:

- [ ] `ar-sa` (Saudi Arabia)
- [ ] `ar-eg` (Egypt)
- [ ] `ar-dz` (Algeria)
- [ ] `ar-tn` (Tunisia)
- [ ] `ar-ye` (Yemen)
- [ ] `ar-jo` (Jordan)
- [ ] `ar-kw` (Kuwait)
- [ ] `ar-bh` (Bahrain)
- [ ] `ar-iq` (Iraq)
- [ ] `ar-ly` (Libya)
- [ ] `ar-ma` (Morocco)
- [ ] `ar-om` (Oman)
- [ ] `ar-sy` (Syria)
- [ ] `ar-lb` (Lebanon)
- [ ] `ar-ae` (U.A.E.)
- [ ] `ar-qa` (Qatar)

Obviously, the most common data should be inherited from the base locale to avoid duplicate data.

Related issues:

- #1439 
- #1440

**Comment by lk-geimfari** [comment]
So if there is anyone who knows Arabic, please let me know.

**Comment by Iten-No-404** [comment]
Hello, I can speak Arabic (from Egypt). How can I help?

**Comment by lk-geimfari** [comment]
@Iten-No-404 ^

**Comment by Iten-No-404** [comment]
Alright, I'll take a look and hopefully start a pull request soon. I'll let you know if I have any questions.
