### ISSUE TITLE
Sunsetting support for older versions of Python.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#1438]
Starting from Mimesis `v12.0.0` we will support only latest versions of Python. 

Namely: 3.10, 3.11, 3.12 and `pypy3.10`

**Comment by phofl** [comment]
Could you update your conda-forge recipes accordingly? You can still pull v12x in for older Python versions with conda

**Comment by lk-geimfari** [comment]
@phofl Unfortunately, I am not the maintainer of [mimesis for conda](https://anaconda.org/conda-forge/mimesis). I'm not sure if there's anything I can do. Let me know if I'm wrong.

**Comment by DManowitz** [comment]
The `pyproject.toml` file still says `python = "^3.8"`

**Comment by DManowitz** [comment]
@phofl, I have filed a bug report and submitted a PR in the [conda-forge mimesis feedstock](https://github.com/conda-forge/mimesis-feedstock) to fix this issue, at least for v12.1.0 and going forward.

**Comment by lk-geimfari** [comment]
I see. My bad. I've fixed `pyproject.toml` now.
