### ISSUE TITLE
Add croatian locale

### ISSUE THREAD

**Issue by CerealKiller0807** [lk-geimfari/mimesis#1467]
Hello,

Planned to create a pull request for the Croatian locale.
I have the code ready in my local environment but get permission denied when trying to publish a new branch on this repository and create a new pull request.

Could you maybe help me with that?

**Comment by lk-geimfari** [comment]
Absolutely! You have to do these steps:

1. Fork this repositry and create new branch from `master`: `git checkout -b croatian-lang-support`
2. See https://github.com/lk-geimfari/mimesis/tree/master/mimesis/data/locale_template
3. Create Pull Request.

**Comment by lk-geimfari** [comment]
You can use `cs` locale as an example. I think these languages may be similar in term of structure.

**Comment by lk-geimfari** [comment]
I've released version 13.0.0 with `Locale.HR` support. See https://github.com/lk-geimfari/mimesis/releases.

Thank you! It's great to have support for Croatian language.

**Comment by CerealKiller0807** [comment]
To answer your question, registrations look like this
HR-XXX-ZZ
or
HR-XXXX-ZZ

Where x is any number and ZZ is usually two characters short for the county :)
