### ISSUE TITLE
generic.pyi has incorrect attribute for providers.Cryptographic

### ISSUE THREAD

**Issue by MarcelWilson** [lk-geimfari/mimesis#1471]
# Bug report

## What's wrong

generic.pyi has incorrect attribute for providers.Cryptographic
https://github.com/lk-geimfari/mimesis/blob/346f62471345186164f06dee6b83020a7ac3c8ba/mimesis/providers/generic.pyi#L21

## How is that should be
```python
    cryptographic: providers.Cryptographic
```

**Comment by lk-geimfari** [comment]
You're right. Thank you for noticing. I'll fix that.
