### ISSUE TITLE
Support python < 3.10

### ISSUE THREAD

**Issue by Aymane11** [lk-geimfari/mimesis#1506]
# Feature request

Support older python versions than 3.10

I've checked the issue #981, but on pypi it still has only python versions >= 3.10

![image](https://github.com/lk-geimfari/mimesis/assets/24499930/68b595b5-de4c-4c7e-866d-1be31434e3d0)

**Comment by lk-geimfari** [comment]
> To work with Mimesis on Python versions 3.8 and 3.9, the final compatible version is Mimesis 11.1.0. Install this specific version to ensure compatibility.


There are no plans to support older Python versions in future releases.
