### ISSUE TITLE
Allow random gender for personal data

### ISSUE THREAD

**Issue by jrast** [lk-geimfari/mimesis#154]
Currently one of 'male' or 'female' must be given (or defaults to 'female') for personal data. It would be nice if the gender would be randomly generated. 

I have made a sample implementation allows to pass `gender=None` to all functions of the personal provider. If None is given, the gender is randomly generated. The implementation can be found here:
https://github.com/jrast/elizabeth/tree/random-gender

The changes can be seen in this commit: https://github.com/jrast/elizabeth/commit/d746eaef612ac328cbc249eb8533ac4366b9d50c

If there is interest, I can create a pull request.

**Comment by lk-geimfari** [comment]
Looks good. PR, please.

**Comment by jrast** [comment]
PR https://github.com/lk-geimfari/elizabeth/pull/155 is out.

Please see also the note about the default in the comment on the pull request.

**Comment by lk-geimfari** [comment]
@jrast Look at comments by @wikkiewikkie in PR #155, please.
