### ISSUE TITLE
Location aware test data

### ISSUE THREAD

**Issue by sdp5** [lk-geimfari/mimesis#1552]
# Feature request

While generating datasets that would be helpful if they can be location aware for the given locale.
`locale_to_country` mapping may not be perfect however can serve the purpose up to an extent.

for example for `DE_AT`, `DE_CH`, `EN_AU`, `EN_CA` etc.

## Thesis

```
>>> from mimesis import Address
>>> address = Address(locale=Locale.EN_AU)
>>> address.country()
'Ethiopia'
>>> address.calling_code()
'+509'
>>> address.city()
'Hopewell'
```
Proposal: return an Australian address.

## Reasoning

Adding little context to it would help test some real scenarios.

**Comment by lk-geimfari** [comment]
I'm not sure it makes much sense, but you could use [Custom Field Handlers](https://mimesis.name/en/master/schema.html#custom-field-handlers) to achieve a similar result.

**Comment by sdp5** [comment]
> I'm not sure it makes much sense, but you could use [Custom Field Handlers](https://mimesis.name/en/master/schema.html#custom-field-handlers) to achieve a similar result.

sure thanks @lk-geimfari !
