### ISSUE TITLE
Add support of GPT provider.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#1567]
If something the user needs is not supported by Mimesis, they can generate it using OpenAI, like this:

```python
from mimesis.plugins.gpt import ChatGPT

>>> chat_gpt = ChatGPT(api_key='API_KEY_HERE')
>>> chat_gpt.assistant_message = "You are a test data generator."
>>> chat_gpt.user_message = (
    "Generate a random {prompt}. "
    "Please make sure that nothing except the {prompt} is in the output."
)
>>> chat_gpt.chat("japanese city name", model="gpt-3.5-turbo")
'翔太'

>>> chat_gpt.image("ninja shiba pixel art") # returns image encoded in base64 (or, maybe as BytesIO object)
```

This is just an [example](https://gist.github.com/lk-geimfari/103365dcb8012d896ac9fca41171debb); the API is not finalized yet.

**Comment by lk-geimfari** [comment]
I'm currently working on this, but help is welcome.

**Comment by Rangeeshar** [comment]
Hi @lk-geimfari , If you are not working on this I could create this plugin from your example code.

**Comment by lk-geimfari** [comment]
> Hi @lk-geimfari , If you are not working on this I could create this plugin from your example code.

Sure!

**Comment by Rangeeshar** [comment]
Hi man, couple of thoughts. For the accessibility should use free LLM to generate the results like random text, image, and audio based on the prompt. It will unlock lot of users who can test us without any subscription to chatgpt plus or to even chatgpt.

**Comment by lk-geimfari** [comment]
> Hi @lk-geimfari , couple of thoughts. For the accessibility should use free LLM to generate the results like random text, image, and audio based on the prompt. It will unlock lot of users who can test us without any subscription to chatgpt plus or to even chatgpt.

I'd prefer to avoid a lot of optional deps, but overall the idea is a good one.

**Comment by Rangeeshar** [comment]
@lk-geimfari  check this draft PR.
https://github.com/Rangeeshar/mimesis/pull/1 Let me know if you need any other change on top of this.

**Comment by lk-geimfari** [comment]
I like it! Looks good. A good idea would be to use try/except when importing libs that will be optional. See the example in plugins/pytest.py. Also, do not foget include optional deps to pyproject.toml so we will be able to install all optional AI-related deps like this:

```
> pip install mimesis[ai]
```

**Comment by lk-geimfari** [comment]
Also, don't forget the tests. Tests are good, we love them.
