### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#169]
When using any kind of `random` in testing we want it to be reproducible. 
Right now all the providers rely on some kind of `random` functions.

So, what I suggest:
1. Create a new optional config entry: `ELIZABETH_RANDOM_SEED` (maybe it should be a parameter somewhere as well?)
2. When it is set, use it's value as a seed

**Comment by lk-geimfari** [comment]
@sobolevn That's good idea. PR would be very handy, if you have free time.

**Comment by sobolevn** [comment]
Not until the next weekends.

**Comment by blakev** [comment]
Does this need to be implemented?

Wouldn't it work just the same if you initialized the seed yourself before calling any generation methods?

**Comment by lk-geimfari** [comment]
@blakev Thank you for contribution, but it's already implemented by @sobolevn in new-structure-feature branch. We will merge it in this weekends.

**Comment by sobolevn** [comment]
@blakev maybe it is indeed a good idea.

@lk-geimfari I guess we should not create our own random, lets use shared `random` instance.
