### ISSUE TITLE
Still failed some tests

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#174]
Basically I fixed the problem with `ImportError`, but code need refactoring.

There are some problems with providers, namely: `Structured()`, `Text()`  and  `Generic()`.

Issue type:
```
TypeError: __init__() takes 1 positional argument but 2 were given
```

Full report [here](https://travis-ci.org/lk-geimfari/elizabeth/jobs/241551298#L4021)

**Comment by axce1** [comment]
i'll try fix it next week

**Comment by lk-geimfari** [comment]
@axce1 Thank you! Keep in mind that this error in [feature-new-strucutre](https://github.com/lk-geimfari/elizabeth/tree/feature-new-strucutre).

**Comment by lk-geimfari** [comment]
I was try to fix this issue, but I could not. All test still failed. Also imports looks very ugly, after refactoring. but otherwise nothing worked.

**Comment by lk-geimfari** [comment]
Above I mean branch feature-new-structure.

**Comment by lk-geimfari** [comment]
@Valerievich If you still interested, you can try fix this.

**Comment by Valerievich** [comment]
Sorry, but full report does not exist.
