### ISSUE TITLE
Error when install elizabeth==0.4.0

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#177]
I have received such a report about issue to my email. It is necessary to correct this error.

```
$ pip install -r requirements.txt 
```
```
...
copying elizabeth/data/int/hardware.py -> build/lib/elizabeth/data/int
error: can't copy 'elizabeth/data/int/__pycache__': doesn't exist or not a regular file
    ---------------------------------------
Command "/home/ryndin/venvs/lean_django/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-snslvlkx/elizabeth/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i0t_c4xx-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ryndin/venvs/lean_django/include/site/python3.5/elizabeth" failed with error code 1 in /tmp/pip-build-snslvlkx/elizabeth/
```

**Comment by MikeWent** [comment]
![image](https://user-images.githubusercontent.com/23062065/27226002-7666a1be-52a5-11e7-887b-a4e177c29af2.png)

I get the same error on pip 9.0.1, Python 3.5.2.

`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g6besmi2/elizabeth/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wnx2745i-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-g6besmi2/elizabeth/`

**Comment by lk-geimfari** [comment]
@MikeWent Please, try install previous version of library. We will fix this issue in 0.4.1. If you want to contribute, you can fix this issue by yourself and send us PR.

**Comment by lk-geimfari** [comment]
@MikeWent Tell me, please, which operation system do you use? Windows? I asked because on Ubuntu everything is okay:

```
(test) ➜  ~  pip install elizabeth
Collecting elizabeth
  Downloading elizabeth-0.4.0.tar.gz (1.8MB)
    100% |████████████████████████████████| 1.8MB 581kB/s 
Building wheels for collected packages: elizabeth
  Running setup.py bdist_wheel for elizabeth ... done
  Stored in directory: /home/lk/.cache/pip/wheels/0c/f0/00/d32b56edc77b96fc038f68b72790137aaa2ed704066c0635f7
Successfully built elizabeth
Installing collected packages: elizabeth
Successfully installed elizabeth-0.4.0
(test) ➜  ~  
```

**Comment by MikeWent** [comment]
@lk-geimfari Ubuntu 16.04 with last updates, pip 9.0.1, Python 3.5.2. I tried to uninstall elizabeth and install again (with pip option `--no-cache-dir`), but got the same error as 3 days ago. 

I also tried on my Android phone (via Termux) and it works. Output below:
```
Installing collected packages: elizabeth
  Running setup.py install for elizabeth ... done
Successfully installed elizabeth-0.4.0
$ pip3 --version
pip 9.0.1 from /data/data/com.termux/files/usr/lib/python3.6/site-packages (python 3.6)
$ python3 --version
Python 3.6.1
```

Maybe I just need to upgrade Python 3.5.2 to 3.6.1 on Ubuntu?

**Comment by lk-geimfari** [comment]
@MikeWent Actually it's should work fine with Python 3.4. I think that problem not in Python.
