### ISSUE TITLE
The name of the library does not reflect its essence.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#188]
When I created this library, it was originally called `church`. I think that is was cool name. I was renamed this library because some people think that is offensive name. Okay, maybe its so.

I renamed library and even without hesitation for some reason gave name `elizabeth`. You know, this name does at all not reflect essence of library. When developer hears name of this library they thinks about Elizabeth II - Queen of Great Britain.

When I import something from this library I'm very annoyed with the way it reads and looks:
```python
from elizabeth import Science # wat?
```

Perhaps this is not a problem and renaming is not a better idea, but it seems to me that this is a big problem. Let's discuss this.

I propose following names:

- fictitious
- falsify
- faktory
- **mimesis**

How it will look if we choice name `mimesis`:

```python
from mimesis import Datetime
```

I think that is much better and if someone of our contributors shares my opinion, then I would rename the library.

**Comment by Valerievich** [comment]
'mimesis' is a good one.

**Comment by lk-geimfari** [comment]
@Valerievich Look at development branch, please. I completely refactored all code. Now wee need to new name and it's will reborn of this project.

**Comment by firestalk** [comment]
+1 for mimesis

**Comment by Valerievich** [comment]
@lk-geimfari May I help with rename? Should I do that in dev.branch?

**Comment by lk-geimfari** [comment]
@Valerievich We will rename library in [this](https://github.com/lk-geimfari/elizabeth/tree/feature-new-strucutre) branch. There's a lot of work. Help will be very handy. Refactor it only using PyCharm or another smart IDE which helps with refactoring and renaming. Be very careful. Thanks.

**Comment by lk-geimfari** [comment]
@Valerievich You can fork feature-new-strucutre branch and tried to rename library.

**Comment by lk-geimfari** [comment]
@Valerievich I already started renaming. Please, loot at the branch: feature-new-structure.

**Comment by lk-geimfari** [comment]
@ryanvarley Hi. Please, check your gmail inbox.

**Comment by Valerievich** [comment]
@lk-geimfari Ok, then I won't disturb you )

**Comment by ryanvarley** [comment]
This a new way of discovering a useful project. We actually use `faker` quite extensively and have found it pretty slow at times, I've shared this with the rest of the team.

I actually went the other with my 'mimesis' project and choose a name that meant nothing (https://github.com/ucl-exoplanets/wayne), so mimesis is all yours 🙂

**Comment by lk-geimfari** [comment]
@ryanvarley Thank you very much. I hope that you find this project useful for you. Thanks again!

**Comment by lk-geimfari** [comment]
So. Library was been renamed. This is final name. We will **never** renamed this library again.

Special thanks @ryanvarley. He gave us new name.
