### ISSUE TITLE
JSON minimzer before publish on PyPI.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#192]
I just [finished](https://github.com/lk-geimfari/elizabeth/blob/feature-new-strucutre/json_minimizer.py) working on simple json minimizer, but it's a very dirty solution. Wee need to refactor it, because it's works to slowly, a dead tortoise runs faster than this script. 

A very important question is will compression affect the performance of the library?  If will then how? Will it become faster or much slower, than now?

Example of locales with minimized data:

Locale: `it`
**Size before**: `368.2 kB`.
**Size after**:  `302.9 kB`.

---

Locale:  `en`
**Size before**: `689.0 kB`.
**Size after**:  `595.7 kB`.

This can show an insignificant gain, but keep in mind that we have 32 locales, each of which has 7 files.

**Comment by lk-geimfari** [comment]
@sobolevn what do you think about it?

**Comment by lk-geimfari** [comment]
@Valerievich @Battleroid Any ideas?

**Comment by sobolevn** [comment]
Sorry, but I could not find source code. A link, please?

**Comment by lk-geimfari** [comment]
It's still good feature. We need to find good script for this.

**Comment by sobolevn** [comment]
https://stackoverflow.com/questions/33233313/python-json-dumpsval-to-output-minified-json ?

**Comment by lk-geimfari** [comment]
@sobolevn I have checked this method and to my surprise, the size of the project only became larger. A first version of minimizer was worked perfectly, but too slowly.

**Comment by lk-geimfari** [comment]
So, i'ts done!

![image](https://user-images.githubusercontent.com/15812620/30799967-31659c5a-a1e7-11e7-8fc3-c8853456ad35.png)


```
python3 setup.py minify
# or
make minify
```

**Comment by sobolevn** [comment]
Nice job!
