### ISSUE TITLE
Update documentation.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#194]
We need update documentation again. I suggest generate documentation with Sphinx again.

**Comment by lk-geimfari** [comment]
Also update PYPI_README.md file.

**Comment by lk-geimfari** [comment]
Looks like our old documentation does not work. We need generate documentation automatically from docstring.

@Valerievich Your help would be very handy. I'll work on locale `ru`. I want to update some data.

**Comment by Valerievich** [comment]
@lk-geimfari OK, I'll do it. I'll start after finish with `ee` locale. I need few days for it.

**Comment by lk-geimfari** [comment]
@I think that code of Estonian language is `et`, not `ee`. [It's just a note](https://msdn.microsoft.com/en-us/library/ms533052(v=vs.85).aspx). Thank you!

**Comment by Valerievich** [comment]
Thanks, I thought we use [this](https://ru.wikipedia.org/wiki/ISO_3166-1) code list.

**Comment by lk-geimfari** [comment]
@Valerievich I [found](https://sphinx-ru.readthedocs.io/ru/latest/) Sphinx documentation in Russian. I thinks that is would helpful.

**Comment by Valerievich** [comment]
@lk-geimfari Please tell me what exactly you expects from this issue? 
We already have `Sphinx` makefile in `\docs`. So I can just execute `make html` and get new ver. of documentation. Would it be enough?

**Comment by lk-geimfari** [comment]
@Valerievich Actually it should work, but i'm not sure. If it's works then it's okay. We need generate API Reference automatically from docstrings.

**Comment by Valerievich** [comment]
You can see what I've got. I used current ver. `conf.py`.  Docstrings are there. `autodoc` is included.
[html.zip](https://github.com/lk-geimfari/mimesis/files/1277666/html.zip)

**Comment by lk-geimfari** [comment]
@Valerievich Unfortunately, only partially. There no new providers, such as `Cryptographic()`. Also we need `.rst` format, which easy to edit.

**Comment by lk-geimfari** [comment]
@Valerievich Can you do it? Please generate autodoc for all providers (`.rst` format) and it's all.

**Comment by Valerievich** [comment]
I'll fit it

**Comment by lk-geimfari** [comment]
@Valerievich Thank you!

**Comment by Valerievich** [comment]
@lk-geimfari Did you create `api.rst`, `guide.rst` manually last time?

**Comment by lk-geimfari** [comment]
@Valerievich Only `guide.rst`. As far as I remember, `api.rst` was created automatically.

**Comment by Valerievich** [comment]
My solution is in PR #223

**Comment by lk-geimfari** [comment]
I understood where is error. We had an interpreter of version 2.7, at the same time in the code for some functions annotations are used, which are the features of Python 3.x. I have changed the interpreter to CPython 3.x and everything is ok!

**Comment by lk-geimfari** [comment]
We need to update documentation again.
