### ISSUE TITLE
Change how Github releases are formated

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#195]
There's a good format to follow: https://github.com/commitizen/cz-cli

See an example of some simple library: https://github.com/sobolevn/recase/releases

**Comment by gnubyte** [comment]
I'll take this and work on it over the next week.
Thanks,
-Gnubyte

**Comment by gnubyte** [comment]
Hi @lk-geimfari & @sobolevn 
https://github.com/gnubyte/mimesis
I have added the commitizen package to my fork of the mimesis package with the default commitizen plugin, and badge addded to the readme.

Are there any plugins that you as main contributors feel need to be included?
The plugins will affect what needs updates need to be added to the `contributing.md` file.

**Comment by gnubyte** [comment]
Also what is the criteria for fulfilling the issue?

Thank you.

**Comment by lk-geimfari** [comment]
I am personally creating changelog and always update release notes on GitHub on every new release. I close this question, but I will return to it if difficulties arise.
