### ISSUE TITLE
Generic providers do not work

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#201]
It's always return data in English. Looks like someone created wrong PR, Travis CI passed it and i merge this PR.

I found issue. It's returns providers without locale: 

https://github.com/lk-geimfari/mimesis/blob/99dfd8275bd212ea2651afb95d843818ec81c15d/mimesis/providers/generic.py#L46

@Valerievich we need to fix it and your help will very handy.

**Comment by sobolevn** [comment]
Regression test will also be very nice.

**Comment by Valerievich** [comment]
I'll try to fix it today.

**Comment by lk-geimfari** [comment]
@Valerievich Thank you!

**Comment by Valerievich** [comment]
I can't understand how to fix this issue by new PL if my previous PL #200 didn't merged. All changes in my fork ```master``` branch.

**Comment by lk-geimfari** [comment]
@Valerievich I have merged your PR. Thank you!
