### ISSUE TITLE
Refactoring in setup.py

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#215]
I suggest refactoring in `setup.py`. @kennethreitz has published [this](https://github.com/kennethreitz/setup.py) great repository. We will use this project as great example of `setup.py` for us.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
Hope you enjoy!

**Comment by lk-geimfari** [comment]
@kennethreitz Yet another cool project by You. Of Course I'm enjoy! Thanks!
