### ISSUE TITLE
Automatically generate changelog.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#219]
We need way to automatically generate changelog. Any ideas?

**Comment by hi-hi-ray** [comment]
Hi! lk-geimfari,
There is a way to automatically generate changelog, using the following lib: https://pypi.python.org/pypi/gitchangelog

:]

**Comment by lk-geimfari** [comment]
@hi-hi-ray Hi! Looks really awesome! Thank you!
