### ISSUE TITLE
Structuring the documentation.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#226]
We have some inconsistency in the documentation, we need to fix it.

What should be done?

- [x] Move description of  all basic features of Mimesis to `index.rst`.
- [x] Add section `Decorators` with examples of using decorators from `decorators.py`.
- [x] Add section `Generate data by schema` with examples of using `Schema()` from `mimesis/schema.py`.
- [x] Add section `Constants` with examples of all available constants from `mimesis/constants/`.
- [x] Add sections `Utilities` with examples of using functions from `mimesis/utils.py`.
- [x] Add section `Builtins Specific Providers` with examples of using ones.

**Comment by lk-geimfari** [comment]
@sobolevn Can you recommend some good example of documentation with good structure for reading? It seems to me that our documentation is somewhat chaotic. It would be great to make documentation consistent.

**Comment by ayushgangrade** [comment]
Hi @lk-geimfari I would like to work on this!

**Comment by mish24** [comment]
@lk-geimfari I want to work on this for hacktoberfest. Anything I should remember for this?

**Comment by lk-geimfari** [comment]
@mish24 I have updates TODO list. Please, look at tasks.

**Comment by Sidsharik** [comment]
@lk-geimfari I am on it. and would love to work on it.

**Comment by lk-geimfari** [comment]
@Sidsharik Yeah, sure! You're assigned. Thanks!

**Comment by sotsugov** [comment]
@lk-geimfari Hello, anything I can help with?

**Comment by lk-geimfari** [comment]
@sotsugov It's done! Thanks!
