### ISSUE TITLE
Something weird is happening

### ISSUE THREAD

**Issue by vchernetsov** [lk-geimfari/mimesis#230]
This module is installed as a "pip install git+https://github.com/lk-geimfari/mimesis@e885cbb71bb4a9a40ef4ca72f6a7f7035cfd77ee" in docker

Looping over Personal objects gives only 2 persons
I just keep it here:

    root@50978a2def4f:/usr/src/app# python
    Python 3.5.4 (default, Sep 13 2017, 14:38:38) 
    [GCC 4.9.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from mimesis import Personal, settings
    >>> for x in range(10):
    ...     p = Personal()
    ...     password = p.password()
    ...     data = {
    ...         'name': p.name(),
    ...         'last_name': p.surname(),
    ...         'password': password,
    ...         'confirm_password': password,
    ...         'email': p.email()
    ...     }
    ...     print (data)
    ... 
    {'password': 'J!5Adi\\h', 'confirm_password': 'J!5Adi\\h', 'last_name': 'Navarro', 'email': 'arpita1984@yandex.com', 'name': 'Laci'}
    {'password': 'y.{Q!QH0', 'confirm_password': 'y.{Q!QH0', 'last_name': 'Barnes', 'email': 'birdseed1999@outlook.com', 'name': 'Leontine'}
    {'password': 'J!5Adi\\h', 'confirm_password': 'J!5Adi\\h', 'last_name': 'Navarro', 'email': 'arpita1984@yandex.com', 'name': 'Laci'}
    {'password': 'y.{Q!QH0', 'confirm_password': 'y.{Q!QH0', 'last_name': 'Barnes', 'email': 'birdseed1999@outlook.com', 'name': 'Leontine'}
    {'password': 'J!5Adi\\h', 'confirm_password': 'J!5Adi\\h', 'last_name': 'Navarro', 'email': 'arpita1984@yandex.com', 'name': 'Laci'}
    {'password': 'y.{Q!QH0', 'confirm_password': 'y.{Q!QH0', 'last_name': 'Barnes', 'email': 'birdseed1999@outlook.com', 'name': 'Leontine'}
    {'password': 'J!5Adi\\h', 'confirm_password': 'J!5Adi\\h', 'last_name': 'Navarro', 'email': 'arpita1984@yandex.com', 'name': 'Laci'}
    {'password': 'y.{Q!QH0', 'confirm_password': 'y.{Q!QH0', 'last_name': 'Barnes', 'email': 'birdseed1999@outlook.com', 'name': 'Leontine'}
    {'password': 'J!5Adi\\h', 'confirm_password': 'J!5Adi\\h', 'last_name': 'Navarro', 'email': 'arpita1984@yandex.com', 'name': 'Laci'}
    {'password': 'y.{Q!QH0', 'confirm_password': 'y.{Q!QH0', 'last_name': 'Barnes', 'email': 'birdseed1999@outlook.com', 'name': 'Leontine'}

**Comment by lk-geimfari** [comment]
It's not issue. Use it like that:

```python
from mimesis import Personal

p = Personal()

for x in range(10):
    password = p.password()
    data = {
        'name': p.name(),
        'last_name': p.surname(),
        'password': password,
        'confirm_password': password,
        'email': p.email()
    }
    print(data)

```
