### ISSUE TITLE
Check tests for duplicates.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#234]
It is possible that some tests are repeated several times without any need. If so, then we need to fix it.

**Comment by n0zg** [comment]
I made a pull request with the spanish translation :)

**Comment by edjroz** [comment]
Making a pull request on the english version

**Comment by pzelnip** [comment]
How does one run the tests?

**Comment by lk-geimfari** [comment]
@pzelnip `make test` or `py.test .`

**Comment by artiemq** [comment]
I will work on this

**Comment by lk-geimfari** [comment]
@artiemq Okay. Thanks!
