### ISSUE TITLE
Add providers to Generic dynamically.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#238]
At this moment it should be done manually, which means that every time a new data provider appears, you must manually add it to Generic (), which is not convenient. I suggest add all providers from `__all__` to Generic() automatically, but we need to save current API.

Any ideas?

**Comment by Marlysson** [comment]
Can you explain more details about that?

The data providers are [this](https://github.com/lk-geimfari/mimesis/tree/master/mimesis/data) ?

And the manually add that you said are the method in ```add_provider``` in ```generic.py``` file?

Automatically that you say is load from data profile folder and run the ```add_provider``` soon after?

**Comment by lk-geimfari** [comment]
I mean this: https://github.com/lk-geimfari/mimesis/blob/master/mimesis/providers/generic.py#L13

**Comment by lk-geimfari** [comment]
It would be awesome to add new provider to generic automatically, i.e from `__all__`. Keep in mind that we use lazy initialization for providers which use `locale`.

**Comment by Marlysson** [comment]
Why some attributes have the underscore and other not?

**Comment by lk-geimfari** [comment]
Because some providers pull data from files when another not. if attribute start with underscore then it use file from `data/locale/provider.json` and we use lazy initialization for ones.

**Comment by Marlysson** [comment]
What you think about read the class in providers folder, and insert it in `__all__ ` list, and the `Generic ` class read this list and call `__new__` from each element.

The problem would be detect when call lazy load or normal load.. The current `_` at begin from attribute.
