### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#258]
I have started to use `mypy`. Aaaand it is not so good right now.

Libraries lack typing support. And I know that `mimesis` support only `python3`.
Do you consider adding type hints?

There are some advantages:
- stricter API
- static analysis support to improve quality

There are some disadvantages:
- type hinting was introduced in `python3.5`, so any version prior to that will have to use special comments or other hacks
- a lot of manual work
- possible API changes

**Comment by lk-geimfari** [comment]
Do you mean annotations? 

Something like this:
```
def function(num: int) -> float:
    pass
```

Right?

**Comment by sobolevn** [comment]
Yes.

**Comment by lk-geimfari** [comment]
I thinks that we can add annotations. What about Python 3.4?

**Comment by lk-geimfari** [comment]
[Seems](https://www.python.org/dev/peps/pep-3107/) like annotations was added in Python 3.0. And we we lose nothing.

**Comment by sobolevn** [comment]
https://www.python.org/dev/peps/pep-0484/

**Comment by lk-geimfari** [comment]
@sobolevn Soooo... What shall we do? Refusing to support Python 3.4 doesn't seem to be a good idea.

**Comment by sobolevn** [comment]
It actually is in some cases. Since upgrading from `3.4` to `3.5` is painless in 90% of situations.

**Comment by lk-geimfari** [comment]
@sobolevn Let's do this!

**Comment by sobolevn** [comment]
Please, note that variable annotations is not supported in `3.5`. https://stackoverflow.com/questions/39971929/what-are-variable-annotations-in-python-3-6/39973133#39973133

**Comment by lk-geimfari** [comment]
@sobolevn I will add annotations for functions and methods. Can i hope for your help with situations which confuse me?

**Comment by lk-geimfari** [comment]
Example:

```python
    def randints(self, amount: int = None, a: int = 1, b: int = 100) -> list:
        """Generate list of random integers.

        :param amount: Amount of elements.
        :param a: Minimum value of range.
        :param b: Maximum value of range.
        :return: List of random integers.
        """

        if not amount:
            amount = 3

        return [self.randint(a, b)
                for _ in range(amount)]
```

**Comment by lk-geimfari** [comment]
Is it right `amout: int = None`. I mean Is it should be integer default value?

**Comment by lk-geimfari** [comment]
@sobolevn How to be if the function returns multiple types using? Should we use `typing` module?

**Comment by lk-geimfari** [comment]
Yet another example which illustrate syntax:

```python
from typing import Callable, Union

def type_to(new_type: Callable[Union[tuple, list],
                               Union[tuple, list]], check_len=False):
    def inner(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            result = new_type(result)

            if check_len and len(result) == 1:
                return result[0]
            return result

        return wrapper

    return inner
```

Is it okay?

**Comment by sobolevn** [comment]
In regular `python` without types I would say that `None` is perfectly fine. 
But in this particular situation it is possible to change `amount=None` to `amount: int = 3`. That what it does anyway, doesn't it?

**Comment by lk-geimfari** [comment]
@sobolevn Problem is in standard python library. `json` module returns both `list` and `dict`.

**Comment by lk-geimfari** [comment]
So, seems like i have found a [solution](https://github.com/python/typing/issues/182).

**Comment by sobolevn** [comment]
With the provided solution there are a lot of uncovered cases, which are valid `json`:
- `[1, [], {}, "z"]`
- `1` and `"a"`

**Comment by bjd2385** [comment]
@lk-geimfari I've already mentioned this in #267, but if one is defaulting the argument to `None`, which is [automatically pushed](https://github.com/python/cpython/blob/fe4ea9cf1ee04f5a60e4ed928d8624b95b031e18/Lib/typing.py#L366) to `type(None)` or `NoneType`, then we should use `typing.Optional[the_type]`. In the example above, we'd have
```python
def randints(self, amount: Optional[int] = None, a: int = 1, b: int = 100) -> list:
        """Generate list of random integers.

        :param amount: Amount of elements.
        :param a: Minimum value of range.
        :param b: Maximum value of range.
        :return: List of random integers.
        """

        if amount is None:
            amount = 3

        return [self.randint(a, b) for _ in range(amount)]
```

**Comment by lk-geimfari** [comment]
@bjd2385 I'll update code using `Optional`.

**Comment by lk-geimfari** [comment]
Sooo, it's done!
