### ISSUE TITLE
Use type hints in docs

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#259]
Connected to https://github.com/lk-geimfari/mimesis/issues/258

There is a plugin for `sphinx` to grab type hints into autodocs: https://github.com/agronholm/sphinx-autodoc-typehints

I guess it should be used.

**Comment by DefaltSimon** [comment]
I'll try to make this work, if you don't mind :)

**Comment by sobolevn** [comment]
Make sure you are in sync with https://github.com/lk-geimfari/mimesis/pull/260

**Comment by DefaltSimon** [comment]
I have already made the necessary changes to convert :rtype: to type annotations and enable the sphinx extension, should I add annotations for parameters like in #260 as well?

**Comment by sobolevn** [comment]
@lk-geimfari could you please help @DefaltSimon ?

**Comment by lk-geimfari** [comment]
@DefaltSimon Yeah, sure. We work on type hints in `type-hinting` branch.

**Comment by DefaltSimon** [comment]
Sure, I'll submit a pull request to that branch when I finish builtins and the base mimesis directory.

**Comment by lk-geimfari** [comment]
@DefaltSimon Thanks for contributing! Don't forget to add yourself to `contributors.md`.

**Comment by lk-geimfari** [comment]
@sobolevn It's done!
