### ISSUE TITLE
Return to cloud version

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#269]
Sometime ago we started https://github.com/wemake-services/elizabeth-cloud

But it had some issues:
- it was very hard to generate schema, because types was not obvious. now we have hints
- api was not stable. there was a restructuring, now it is done

I guess it is possible to restart that old project to provide a service.
It would also be required to change url and name.

**Comment by lk-geimfari** [comment]
@sobolevn I agree. I'll try work on it when i finish working on `type-hinting` .

**Comment by shivanikohlii** [comment]
Could you please elaborate on this issue, the specs, etc.

**Comment by lk-geimfari** [comment]
@shivanikohlii Thank you for your interest. We have a cloud version of mimesis based on Sanic and GraphQL. So wee needs to update [mimesis-cloud](https://github.com/wemake-services/mimesis-cloud) to support the latest version of Mimesis.

For more details, you can ask a question to @sobolevn.

**Comment by sobolevn** [comment]
@lk-geimfari ?

**Comment by lk-geimfari** [comment]
@sobolevn Oh, sorry. Accidentally closed this one.
