### ISSUE TITLE
setup.py encoding error   (python 2.7.3, debian)

### ISSUE THREAD

**Issue by tamlt2704** [lk-geimfari/mimesis#271]
step 1: clone repository
step 2: cd mimesis && pip install . 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-qr3xMU-build/setup.py", line 31, in <module>
        with open('PYPI_README.rst', 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qr3xMU-build/

python --version # --> 2.7.13, 
uname -a # --> Linux debian 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux

**Comment by lk-geimfari** [comment]
We don't support old version of Python, sorry.
