### ISSUE TITLE
Numbers.primes returns odd numbers, not primes

### ISSUE THREAD

**Issue by faheel** [lk-geimfari/mimesis#280]
The logic for primes in `Numbers.primes` is incorrect, and is instead for odd numbers:
```py
nums = array.array('L', (i for i in range(start, end) if i % 2))
return nums.tolist() if to_list else nums
```

**Comment by faheel** [comment]
The docstring for it is also incorrect. I'll send a PR with the fixes soon.

**Comment by lk-geimfari** [comment]
@faheel Thank you for find this bug. I'll wait for your PR.
