### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by vladcalin** [lk-geimfari/mimesis#284]
There is a broken link in http://mimesis.readthedocs.io/#locales

The broken link points to http://mimesis.readthedocs.io/en/latest/locales.html but there is no such page.

Also, where can I find the supported locales?

**Comment by lk-geimfari** [comment]
@vladcalin You can find supported locales in [README.md](https://github.com/lk-geimfari/mimesis#locales).

**Comment by lk-geimfari** [comment]
@vladcalin I'll fix it ASAP.
