### ISSUE TITLE
Telephone numbers are incorrect

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#287]
Country code can not be less than `1`.

`telephone()` method uses `custom_code` to generate a phone number, but there this rule is not respected: https://github.com/lk-geimfari/mimesis/blob/master/mimesis/utils.py#L205

As it can generate something like `+0-(...)-...`

Reference: https://countrycode.org/

**Comment by lk-geimfari** [comment]
@sobolevn Thank you! I'll fix it today.

**Comment by lk-geimfari** [comment]
Fixed in f5c4df2.
