### ISSUE TITLE
Using enum for clear API

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#288]
This proposal was originally borned in our discussion [here](https://github.com/lk-geimfari/mimesis/commit/31614c6a09d964a59381fc16fc63992b976092a2#commitcomment-25635904).

Proposal (by @sobolevn):

"_Maybe we could use enums more often?
It really covers this case easily. And it is possible to statically check your code with enum._"

Here's the sample code:

```python
from enum import Enum

class PortRange(Enum):
      DEFAULT = (1, 65535)
      WELL_KNOWN = (1, 1023)
      EPHEMERAL = (49152, 65535)
      REGISTERED = (1024, 49151)
```

And then:
```python
def port(self, range_: PortRange = PortRange.DEFAULT) -> int:
```

So, we want to discuss with community what is better? Let's discuss.

If you like this idea, add :+1:, otherwise :-1:.

**Comment by lk-geimfari** [comment]
As for me, I like the idea, but with some notes:

1. When we will use `enums` we should import one, if we want to change default values of arguments of the methods:

```python
>>> from mimesis import Internet, Personal
>>> from mimesis.enums import PortRange, Gender
>>>
>>> per = Personal()
>>> female_name = per.full_name(gender=Gender.FEMALE)
>>>
>>> net = Internet()
>>> port = net.port(range_=PortRange.EPHEMERAL)
```

**Comment by lk-geimfari** [comment]
@sobolevn So, i refactored [check_gender](https://github.com/lk-geimfari/mimesis/blob/master/mimesis/utils.py#L144) using enum and it's how it looks now:

```python
from mimesis.enums import Gender

def check_gender(gender: Gender = Gender.DEFAULT) -> str:
    if gender in Gender:
        return gender.value
    else:
        raise AttributeError('You should use Gender from module  enums')
```

If it's correct way to use `enum`, then i really like how it looks. This is awesome!

**Comment by sobolevn** [comment]
Yes, it looks nice. But what is `Gender.DEFAULT`? It is not clear to me without going into the docs. It really should be `Gender.MALE`.

**Comment by lk-geimfari** [comment]
@sobolevn It's for returning random gender, maybe it's good idea to rename it to `RANDOM`?

**Comment by lk-geimfari** [comment]
@sobolevn Should we use enums in methods everywhere or only where we have `try/except/KeyError`?

**Comment by sobolevn** [comment]
@lk-geimfari sorry, I don't get it. Could you provide a code example to illustrate your point?

**Comment by lk-geimfari** [comment]
@sobolevn For example

```python
    def mime_type(self, type_t: str = 'application') -> str:
        """Get a random mime type from list.

        :param str type_t:
            Type of media: (application, image, video, audio, text, message).
        :return: Mime type.
        :raises ValueError: if type_t is not supported.
        """
        supported = ' '.join(MIME_TYPES.keys())

        if type_t not in list(MIME_TYPES.keys()):
            raise ValueError(
                'Unsupported mime type! Use: {}'.format(supported))

        mime_type = self.random.choice(MIME_TYPES[type_t])
        return mime_type
```

We can rewrite it using `enums` like this:
```python
    def mime_type(self, type_: MimeType = MimeType.RANDOM) -> str:
        """Get a random mime type from list.

        :param type_: Enum object MimeType.
        :return: Mime type.
        :raises ValueError: if type_t is not supported.
        """
        if type_ and type_ in MimeType:
            return self.random.choice(MIME_TYPES[type_])
        else:
            raise TypeError("You should use enum object MimeType")
```

I want to understand which solution is clearer in terms of design. Or, perhaps, both solutions are bad?

**Comment by sobolevn** [comment]
I like the second one. That was my original point, when I have fired an issue.

I am not sure about `RANDOM` by the way. I have heard a lot of developers said that it does not belong there. That `enum` represent items. `RANDOM` is not an item. 

Maybe it is not to late to replace it with a function?

```python
 def mime_type(self, type_: Optional[MimeType] = None) -> str:
        if type_ is None:
              type_ = select_random_item(MimeType)
        ...
        return self.random.choice(MIME_TYPES[type_.value])
```
