### ISSUE TITLE
How i can create two telephones for one person?

### ISSUE THREAD

**Issue by 4kpt** [lk-geimfari/mimesis#292]
```python
from mimesis import Personal
a = Personal("en")
b = Personal("en")
assert a.telephone('+#-(###)-###-####') == b.telephone('+#-(###)-###-####')
```

**Comment by 4kpt** [comment]
I need two different telephones like work phone and home phone. How can i get it?

**Comment by lk-geimfari** [comment]
@4kpt There are bug with generating telephone by mask which was be fixed in version `1.0.0. I'll publish new version in next week.

Try use this:

```
>>> from mimesis import Code
>>> a = code.custom_code('+#-(###)-###-####')
>>> b = code.custom_code('+#-(###)-###-####')
>>> a
'+3-(289)-022-8253'
>>> b
'+3-(504)-942-9931'
>>> 
```

We have seriously improved the library in version 1.0.0 and these inconveniences should pay off by clearer API.

**Comment by 4kpt** [comment]
But i need use usa-specific phone number like Person("en").telephone...
Why create new Person instance return old person telephone?

**Comment by lk-geimfari** [comment]
@4kpt We have discussed why in #286. It's a bug related to `code.Code.custom_code`: [details](https://github.com/lk-geimfari/mimesis/issues/286#issuecomment-344685919).

**Comment by lk-geimfari** [comment]
@4kpt If you are really really need usa telephone numbers, then you can use this monkey-patch:

```
>>> import random

>>> from mimesis import Personal, Code
>>> code = Code()
>>> masks = Personal('en').data['telephone_fmt']
>>> a = code.custom_code(mask=random.choice(masks))
```

**Comment by 4kpt** [comment]
Thanks.
