### ISSUE TITLE
Need support of other locales.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#3]
We need to add:

- 🇷🇴 Roumanian
- 🇱🇹 Lithuanian
- 🇱🇻 Latvian

Feel free to send us request for another language which not in list.

**You should use**: [locale_template](https://github.com/lk-geimfari/mimesis/tree/master/mimesis/data/locale_template)

**Comment by lokhi** [comment]
I can help you with french if you want

**Comment by lk-geimfari** [comment]
@lokhi If something is missing, then add, please. If something in data is a wrong then fix this, please. Thank you very much!

**Comment by lokhi** [comment]
Thanks I will check that ;)

**Comment by auyer** [comment]
I can help with Brazilian Portuguese !

**Comment by lk-geimfari** [comment]
@auyer It would be awesome! I [added](https://github.com/lk-geimfari/church/tree/master/church/data/pt-br) folder for pt-br locale. Please, check out what data we need. Thank you for your contribute!

**Comment by Hellowlol** [comment]
much of the data from countries  can be found on Wikipedia. Like list of cites, names etc. would be nice to use a script to fix this

**Comment by lk-geimfari** [comment]
@Hellowlol Yeah, i use `BeautifulSoup` for grabbing some data from another sites. For grabbing from Wikipedia i use Chrome [extension](https://chrome.google.com/webstore/detail/copytables/ekdpkppgmlalfkphpibadldikjimijon) that helped copping a column from a table.

**Comment by jackmcmorrow** [comment]
Hey @auyer ! I want to help with ptbr too! Hit me up and we can work on it together!

**Comment by jackmcmorrow** [comment]
Here is a list of brazilian cities with more than 100.000 inhabitans. That's 300+ names in a table.

**Comment by jackmcmorrow** [comment]
Oops, forgot the link https://pt.m.wikipedia.org/wiki/Lista_de_municípios_do_Brasil_acima_de_cem_mil_habitantes

**Comment by auyer** [comment]
@jackmcmorrow Sure ! Thanks ! I'll push my changes to my fork. You can make PRs there ! https://github.com/auyer/church

**Comment by yebrahim** [comment]
Are you looking for RTL languages too?

**Comment by lk-geimfari** [comment]
@yebrahim Yes, but I do not know how to work with these data. So, if you know how to add data for RTL locale correctly then i support your decision.

**Comment by theomessin** [comment]
Want to help with Greek!

**Comment by lk-geimfari** [comment]
@theomessin Perfect! Let me know when you can do it, please. I can add needed folder and json files

**Comment by theomessin** [comment]
@lk-geimfari If you could just add the folder and json files that'd be great! I'll start as soon as possible 😄

**Comment by lk-geimfari** [comment]
@theomessin Oh, okay. I add all needed tonight. Σας ευχαριστούμε!

**Comment by lk-geimfari** [comment]
@theomessin I [added](https://github.com/lk-geimfari/church/tree/master/church/data/el) folder and files for Greek.

**Comment by modkaffes** [comment]
@theomessin @lk-geimfari I'd like to help with greek too! I've started work [here](https://github.com/modkaffes/church/pull/1). @theomessin, want to split files?

**Comment by lk-geimfari** [comment]
@modkaffes It's great! Thank you!

**Comment by lk-geimfari** [comment]
When you add a new language, take into account #47

**Comment by cleac** [comment]
@lk-geimfari hi, I can help with Ukrainian language :smile:  Currently have some work to do, but in a week I'll have a plenty of time

**Comment by lk-geimfari** [comment]
@cleac It's great! Thank you!

**Comment by redus** [comment]
need help with CJK langs? could provide some help as well

**Comment by lk-geimfari** [comment]
@redus If you can add all data completely for one locale which you want it would be really awesome!  Thank you!

**Comment by Uncleleech** [comment]
I can help with English (GB). I'll give it a look in a while.

**Comment by lk-geimfari** [comment]
@Uncleleech It would be great. Thank you!

**Comment by Uncleleech** [comment]
@lk-geimfari quick question, does cities include everything (towns, villages) or just cities. I see in the En-Us there is everything but in the UK the definition of city is pretty specific.

Can I just add another list of 'towns' or will this break stuff?

**Comment by lk-geimfari** [comment]
@Uncleleech Do this, as will be better for UK. 

Regarding the 'states', then they are called "subjects" in Russian, "province" in some other countries. We use the 'states' for all locales in JSON, so it was easier to work with data.

**Comment by jasonwaiting-dev** [comment]
I can help with Japanese & Chinese. 
Have a quick question, there are full width & half width characters in Japanese.
https://en.wikipedia.org/wiki/Half-width_kana
How should I deal with different character sets in elizabeth? I will create full width version first.

**Comment by lk-geimfari** [comment]
@jasonwaiting-dev You can use `ko` (Korean) as example. Unfortunately, I never worked with the Chinese and Japanese.

**Comment by redus** [comment]
@jasonwaiting-dev I was unaware there was a difference between the two in Japanese and have no idea how often it's used. 

I think the best way should be just provide the full width version first. If the need arises, make a separate locale like ja-half, unless there is an algorithm switching between the two then we should make it available at specific_providers.py

**Comment by jasonwaiting-dev** [comment]
@redus it's kind of strange coz some old systems, especially banking systems, in japan are still using half-width characters in database, e.g. アイウエオ (full width) becomes ｱｲｳｴｵ (half width).

I agree that we should just provide full width version at this moment. I am creating jp version now.

**Comment by redus** [comment]
@jasonwaiting-dev are you making alphanumeric full-width as well? I don't know full-width alphanumeric characters are used or not as well (ＡＢＣＤ０１２３). I believe simple dictionary from full width char to half width char should do it, without any separate locale.

**Comment by jasonwaiting-dev** [comment]
@redus sorry for the late reply. Both full-width and half-width alphanumeric characters are being used in Japan. I notice that the usage of half-width alphanumeric characters with full-width japanese characters is more popular now but I can still find a number of webpages using full-width characters only. 
I think I'll stick to half-width alphanumeric with japanese characters atm.

> believe simple dictionary from full width char to half width char should do it, without any separate locale.

yes, we may discuss how to deal with this later. I think we only have this problem in japanese locale.

**Comment by jlwt90** [comment]
Hi @lk-geimfari, I can help on Chinese translation. There are a numbers of variations in Chinese language (https://en.wikipedia.org/wiki/Chinese_as_an_official_language).

I think I'll start with **People's Republic of China** version.

**Comment by lk-geimfari** [comment]
@jlwt90 That's great! Thank you!

**Comment by el** [comment]
I made a PR for Turkish #122

**Comment by PaulWaltersDev** [comment]
Hello All, would you mind if I could create a locale for English (AU)? It would be largely similar to English (GB) except for place and state names, postcode, some business details, a few unique swear words and Aus word spellings.

I'm also French-speaking so can help in that area if you wish.

**Comment by lk-geimfari** [comment]
@PaulWaltersDev We already have have `en-au` and `fr`. Can you check correctness of `fr` and update `en-au`?

**Comment by PaulWaltersDev** [comment]
Regarding en-au, I had a look at elizabeth/data (master branch) and saw only json files for en and en-gb. Neither of them have Australia--specific content. Where can I find it?

I am happy to check en-au and fr. Will let you know when it's done. :-)

**Comment by lk-geimfari** [comment]
@PaulWaltersDev Oh, sorry i forget remove en-au from .gitignore file. Check it now, please.

**Comment by PaulWaltersDev** [comment]
No probs. Got the latest version now and made additions to en-au. Will test, commit and push for your perusal.

I'm English so might also have a go at checkinv en-gb for any errors.

**Comment by lk-geimfari** [comment]
@PaulWaltersDev Okay. Thank you!

**Comment by PaulWaltersDev** [comment]
@lk-geimfari  Just committed updates to en-au (all except datetime.json which is perfect as it is). Please see commit comments and let me know what you think.

**Comment by lk-geimfari** [comment]
@PaulWaltersDev Of course, but where i can look at your commits? You have only two repositories and and `Elizabeth` was not among them.

**Comment by PaulWaltersDev** [comment]
@lk-geimfari sorry, not had a lot of experience with Github and it shows. You can see the Elizabeth repository and changes now. Submitted a pull request with details included.

**Comment by uvegla** [comment]
Hi @lk-geimfari, I would like to contribute to the hungarian language. If that is okay I will start with a pull request on some basic missing things like the alphabet, colors etc. then move on to chemical elements and so on.

**Comment by lk-geimfari** [comment]
@uvegla It would be awesome! Current version of hungarian has been added by myself. I hope that is not too awful. Check it all, please. Thanks!

**Comment by zelds** [comment]
Hi. Ur u still need help with Ukrainian ?

**Comment by lk-geimfari** [comment]
@zelds Yes, can you help us?

**Comment by lk-geimfari** [comment]
@zelds You can check data for `ru`. I think that the structure of this locales will similar.

**Comment by zelds** [comment]
@lk-geimfari Yeap. I will fork ur project and start working.

**Comment by jlwt90** [comment]
@lk-geimfari sorry, I was quite busy in the past few weeks. I'll work on the Chinese translation later this week!

**Comment by lk-geimfari** [comment]
@jlwt90 @zelds Thank you, guys!

**Comment by zelds** [comment]
@lk-geimfari w8 submit my pull requests. Make 50% of work.

**Comment by lk-geimfari** [comment]
@zelds Please look at the [comments](https://github.com/lk-geimfari/elizabeth/pull/149#issuecomment-285964220). Thank you.

**Comment by bbb1991** [comment]
@lk-geimfari I can help you with kazakh locale if you want

**Comment by lk-geimfari** [comment]
@bbb1991 It is awesome. We are always glad for new locales!

**Comment by Valerievich** [comment]
I'll add "Estonian" locale. I have estonian friend )

**Comment by lk-geimfari** [comment]
@Valerievich That is cool! We'll wait PR.

**Comment by AnChan1** [comment]
I could help with german :)

**Comment by lk-geimfari** [comment]
@AnChan1 Thank you! Please, check correctness of  data for `de` and `de-ch` locales. Also, you can add [builtins specific provider](https://github.com/lk-geimfari/mimesis#builtins-specific-data-providers) for German.

**Comment by mistermantas** [comment]
Is Lithuanian done yet? If not, can I / how can I start helping? 🙂

**Comment by lk-geimfari** [comment]
@mistermantas Of course you can! Thank you! 

P.S Code is `lt`. Just copy files from other locale and replace them with `lt` data.

**Comment by mistermantas** [comment]
@lk-geimfari Easy enough. I'll submit a PR as soon as I can.

Happy Hacktoberfest lol

**Comment by lk-geimfari** [comment]
@mistermantas Thank you! Happy Hacktoberfest! :octocat:

**Comment by lk-geimfari** [comment]
@mistermantas I have pushed [template of locale with instruction](https://github.com/lk-geimfari/mimesis/tree/master/mimesis/data/locale_template).
