### ISSUE TITLE
One time default locale initialization.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#302]
I suggest a feature for changing the default locale:

```python
from mimesis import Personal, Datetime
from mimesis.utils import initialize_default_locale

# First initialize custom default locale
initialize_default_locale('de')

# Create objects with locale de as default.
p = Personal()
d = Datetime()

# Now de is default locale for all data providers:

p.full_name()
# Output: Swanhild Holtzer

d.day_of_week()
# Output:  Mittwoch
```

**Comment by lk-geimfari** [comment]
@sobolevn What do you think?

**Comment by sobolevn** [comment]
What are your agruments?

**Comment by lk-geimfari** [comment]
Using this function, user can pass typing of locale name for every providers.
We just "says" to mimesis that in our project we interested only in this locale.

This:

```python
from mimesis import Personal, Address, Datetime
from mimesis.utils import initialize_default_locale

initialize_default_locale('de')

perspnal = Personal()
address = Address()
datetime = Datetime()
```

Instead this:

```python
from mimesis import Personal, Address, Datetime

perspnal = Personal('de')
address = Address('de')
datetime = Datetime('de')
```

There no need explicitly pass an argument `locale` to the data provider.


**P.S** Yes, we have `Generic` for this cases, but it works slowly because it has a lot of lazy attributes.
I think that this is a fast alternative for one-time locale initialization mechanism which we use in `Generic`.

It's possible that I have passed something important and this is a bad design.
If so, then I'll happy y heard criticism.

**Comment by sobolevn** [comment]
Something does not seem good to me. I can not express it yet. When I will have some spare time I will return to this topic, ok?

**Comment by lk-geimfari** [comment]
@sobolevn Sure. I'll not work on this yet.

**Comment by sobolevn** [comment]
Ok, let's get back to it. Here are my thoughts:

- I feel like this feature might not be 100% thread safe
- It does not really save any time, since it is not that hard to specify a locale
- This might cause some very hard issue, imaging `initialize_default_locale` been called in some very unexpected place. And having a global mutable state is generally a bad practice

**Comment by lk-geimfari** [comment]
@sobolevn I had time to think about it and I came to the same conclusions. The global state is really hard to debug and we'll not add this feature.
