### ISSUE TITLE
Add important data generators for RussiaSpecProvider

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#318]
It would be awesome to add support for generating the following:

- [x] `ИНН` - [Read more on wiki](https://ru.wikipedia.org/wiki/Идентификационный_номер_налогоплательщика).
- [x] `ОГРН` - [Read more on wiki](https://ru.wikipedia.org/wiki/Основной_государственный_регистрационный_номер).
- [x] `КПП` - [Read more on wiki](https://ru.wikipedia.org/wiki/Идентификационный_номер_налогоплательщика#%D0%9A%D0%BE%D0%B4_%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D1%8B_%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8_%D0%BD%D0%B0_%D1%83%D1%87%D0%B5%D1%82_(%D0%9A%D0%9F%D0%9F)).
- [x] `СНИЛС` - [Read more on wiki](https://ru.wikipedia.org/wiki/Страховой_номер_индивидуального_лицевого_счёта).
- [x] `БИК` -  [Read more on wiki](https://ru.wikipedia.org/wiki/Банковский_идентификационный_код).

**Comment by fried-sausage** [comment]
Russian Address Classifier aka [КЛАДР](https://ru.wikipedia.org/wiki/%D0%9A%D0%9B%D0%90%D0%94%D0%A0), or may be more recent: https://ru.wikipedia.org/wiki/ФИАС could also be useful

**Comment by lk-geimfari** [comment]
@fried-sausage Suse! I have updated list.

**Comment by fried-sausage** [comment]
@lk-geimfari btw, if im not mistaken, the only method to generate random numeric string using mask is `pin` method in Code provider. I use it, but not for generating pin codes.
May be it could make sense to add such generic ("Provider-agnostic") methods to BaseProvider or make some generic  provider and add such methods to it?

**Comment by lk-geimfari** [comment]
@fried-sausage Already! Function `utils.custom_code` which also used by `Code.pin`.
