### ISSUE TITLE
Seed does not work for some providers

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#325]
**Description:**
Seems like @duckyou have found a bug in our code and `seed` is really does not work sometime and we should fix it.

**Reason:**
It's happening because we use `custom_code` which use another `random` object.

**Decision:**
We should move utils which use `random` to `helpers.Random`

**Comment by duckyou** [comment]
Thanks for the quick response, @lk-geimfari :smile:

I can try moving `custom_code` to `BaseProvider` like you said in #324  discussion

**Comment by lk-geimfari** [comment]
@duckyou You know, it's better to move it to `helpers.Random`. There's just everything related to random selection.

**Comment by lk-geimfari** [comment]
@duckyou after that, we can just call `self.random.custom_code`. Looks good.

**Comment by lk-geimfari** [comment]
@duckyou If you don't want to do it, I can do it by myself, but if you want work on it, then, please, create new PR, because old is really hard to read :smile: . Thanks!

**Comment by duckyou** [comment]
@lk-geimfari Hmm... You goddamn right!
That's may be simplest solution :relaxed:

I do this ;)

**Comment by lk-geimfari** [comment]
@duckyou Thank you!

**Comment by duckyou** [comment]
@lk-geimfari
https://github.com/lk-geimfari/mimesis/blob/af9c877d9bde654dff2f8be524b81a35460f2307/mimesis/enums.py#L6-L12

Method get_random_item also affected :worried:

**Comment by lk-geimfari** [comment]
@duckyou We will not change it, because it's not really about `data`, but about `arguments` for function.

**Comment by duckyou** [comment]
@lk-geimfari Issue explain:

```python
>>> from mimesis import Address
>>> from mimesis.enums import CountryCode
>>> a = Address(seed=42)
>>> a.country_iso_code(fmt=CountryCode.ISO3)
'NIC'
>>> a.country_iso_code(fmt=CountryCode.ISO3)
'BRN'
>>> a.country_iso_code(fmt=CountryCode.ISO3)
'ARM'
>>> a = Address(seed=42)
>>> a.country_iso_code(fmt=CountryCode.ISO3)
'NIC'
>>> a.country_iso_code(fmt=CountryCode.ISO3)
'BRN'
>>> a.country_iso_code(fmt=CountryCode.ISO3)
'ARM'
...
```
This worked because we set format directly
... but if we omit this parameter

```python
...
>>> a = Address(seed=42)
>>> a.country_iso_code()
'558'
>>> a.country_iso_code()
'096'
>>> a.country_iso_code()
'ARM'
>>> a = Address(seed=42)
>>> a.country_iso_code()
'NIC'
>>> a.country_iso_code()
'096'
>>> a.country_iso_code()
'051'
```
its happen beause:
https://github.com/lk-geimfari/mimesis/blob/af9c877d9bde654dff2f8be524b81a35460f2307/mimesis/providers/address.py#L147-L148

**Comment by lk-geimfari** [comment]
@duckyou Skip this for now. I'll think about it later. Our priority for a right now is `custom_code`.

**Comment by lk-geimfari** [comment]
Fixed. Now we should think about how should we test providers with seed.

**Comment by duckyou** [comment]
@lk-geimfari good job! 😸 
Sorry for off-top, but maybe this project community have a place for discussions.. for example irc or slack?

**Comment by lk-geimfari** [comment]
@duckyou It's okay. Unfortunately, not yet. We have a small community, so usually, we discuss everything here, although it would be great, of course, to have a place where we could discuss everything.

We can create repository `discussion` in @mimesis-lab. I can add you to the team if you're interested in this project.

**Comment by lk-geimfari** [comment]
@duckyou I have invited you to @mimesis-lab. Accept the invitation if you're interested. Thanks!

**Comment by duckyou** [comment]
@lk-geimfari im in! ^^

**Comment by duckyou** [comment]
@lk-geimfari don't forget about https://github.com/lk-geimfari/mimesis/issues/325#issuecomment-352364359 ?

Heres two problems: `AllowRandom.get_random_item` and `ValidateEnumMixin._validate_enum`

Ok.. firstly how to get random enum with seed?
Original realisation is:
https://github.com/lk-geimfari/mimesis/blob/217e5fa7775389b92a166f643276b2533a5fb45e/mimesis/enums.py#L11-L12
aka we can just do this `self.random.choice(list(CountryCode))` without mentioned method

and if we create this simple hack in `AllowRandom` metaclass:
```python
    def __getitem__(self, index):
        if isinstance(index, int):
            return list(self._member_map_)[index]
        return super().__getitem__(index)
```
we can do now  `self.random.choice(CountryCode)` :wink:

**Comment by lk-geimfari** [comment]
@duckyou Also we can add method `get_enum_item()` to `helpers.Random`.

```python
def get_enum_item(self, enum: Optional[Any] = None):
    return self.choice(list(self)) 
```

What do you think? In my opinion, it will be easier.

**Comment by lk-geimfari** [comment]
In this case, we should move `_validate_enum()` to `BaseProvider`

**Comment by duckyou** [comment]
@lk-geimfari 
hmmm `self.random.get_enum_item(CountryCode)` or `self.random.choice(CountryCode)`
... also enum attribute always should be passed to get_enum_item method
but if we combine this with _validate_enum...
```python
key = self.random.get_enum_item(fmt, CountryCode)
```

**Comment by lk-geimfari** [comment]
@duckyou Stop stop. Seems like the solution which I suggested above will not work, it seems.

Do you suggest something like this?
```python
class Enum(enum.Enum):
    def __getitem__(self, index):
        if isinstance(index, int):
            return list(self._member_map_)[index]
        return super().__getitem__(index)

class PortRange(Enum):
    ALL = (1, 65535)
    WELL_KNOWN = (1, 1023)
    EPHEMERAL = (49152, 65535)
    REGISTERED = (1024, 49151)
```

**Comment by duckyou** [comment]
@lk-geimfari Not exactly. But seems like my solution not work too :disappointed:

**Comment by lk-geimfari** [comment]
@duckyou The problem that we need to handle different cases. For example, sometime we need the value of the enum, but sometimes we need item of enum object, i.e `Enum.ITEM`.

**Comment by duckyou** [comment]
Oh... here is:
```python
class MimEnumMeta(EnumMeta):
    def __getitem__(self, index):
        if isinstance(index, int):
            return list(self)[index]
        return super().__getitem__(index)


class PortRange(Enum, metaclass=MimEnumMeta):
    ALL = (1, 65535)
    WELL_KNOWN = (1, 1023)
    EPHEMERAL = (49152, 65535)
    REGISTERED = (1024, 49151)

...
```
Now:
```python
>>> from mimesis import enums
>>> import random
>>> pr = enums.PortRange
>>> pr
<enum 'PortRange'>
>>> pr['ALL']
<PortRange.ALL: (1, 65535)>
>>> pr.ALL
<PortRange.ALL: (1, 65535)>
>>> pr[0]
<PortRange.ALL: (1, 65535)>
>>> random.choice(pr)
<PortRange.REGISTERED: (1024, 49151)>
>>> random.choice(pr) in enums.PortRange
True

```

**Comment by lk-geimfari** [comment]
@duckyou I'll wait for your PR. Keep in mind that we have `builtins` data providers and that sometimes we need an item of the enum, but not a value (`personla.py -> surname`, `payment.py -> credit_card_number`).

**Comment by duckyou** [comment]
@lk-geimfari Can i also move `_validate_enum()` to `BaseProvider`, like you say here https://github.com/lk-geimfari/mimesis/issues/325#issuecomment-353350713 ?

**Comment by lk-geimfari** [comment]
@duckyou If we do it, then tests will fail because `ValidateEnumMixin` used in `mimesis.builtins`. It's really hard to understand what is better. At this moment we can only experiment with solutions.

**Comment by duckyou** [comment]
@lk-geimfari I see here several solutions:

1. Just pass random object to method
2. Like you say here https://github.com/lk-geimfari/mimesis/issues/325#issuecomment-353350713
3. Init random object in ValidateEnumMixin
4. Just in provider method validate enum and raise exception

**Comment by lk-geimfari** [comment]
@duckyou Let's will weigh the pros and cons of all solutions.

**Comment by lk-geimfari** [comment]
@duckyou We need to take a decision that will allow us to make the minimum number of changes.

**Comment by lk-geimfari** [comment]
@duckyou I have found a new problem:
Seeded `full_name()` returns different data because there are two different methods with similar `seed`, i.e `name` and `surname`.

And this is only the tip of the iceberg I think. Now I'm tired and can not figure out why the data is changing for fixed seed, sorry.

I have created PR where you can see changes: https://github.com/lk-geimfari/mimesis/pull/332

**Comment by lk-geimfari** [comment]
Seems like `builtins` providers also does not support of seed. We should fix it!
