### ISSUE TITLE
Add tests for seeded providers

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#335]
As we discussed with @duckyou. We should add tests for seeded providers.

**Comment by duckyou** [comment]
@lk-geimfari use seed tests design like i say here https://github.com/mimesis-lab/discussion/issues/1#issuecomment-353059935?
or is there a more right solution?

**Comment by lk-geimfari** [comment]
@duckyou Actually I have not a better solution right now. @sobolevn maybe you can recommend something? What do you think about solution above?

**Comment by duckyou** [comment]
@lk-geimfari, @sobolevn Example of seed tests: https://github.com/duckyou/mimesis/commit/c59e5d8db6fc9ecd3ba3dd53f5ae4ea1a2636d07
With your approval, I will continue to write tests 😉

**Comment by lk-geimfari** [comment]
@duckyou Looks pretty clear to me. Anyway, I don't see another clearer way to tests seed than this. I'm for, if @sobolevn does not offer something else.

**Comment by lk-geimfari** [comment]
@duckyou So, you can continue to write tests for all providers. Thanks!
