### ISSUE TITLE
pytest-benchmark integration?

### ISSUE THREAD

**Issue by duckyou** [lk-geimfari/mimesis#338]
What about [pytest-benchmark](http://pytest-benchmark.readthedocs.io/en/stable/) integration?
It can be useful for optimization issues
![screenshot_2017-12-28_12-20-41](https://user-images.githubusercontent.com/9839155/34406350-91f1f704-ebc9-11e7-8611-010ac80af9a0.png)
![screenshot_2017-12-28_12-23-30](https://user-images.githubusercontent.com/9839155/34406419-f3517fa6-ebc9-11e7-898c-8aa9f8ab0e73.png)

**Comment by lk-geimfari** [comment]
@duckyou It's can be useful I think. Let's add it!

**Comment by duckyou** [comment]
@lk-geimfari PR to `master`? Or you can create `dev` branch for features and after review merge it with master?

**Comment by lk-geimfari** [comment]
@duckyou Can you create a branch, please?
```
git checkout bench
git add --all
git commit -m "Added integration with pytest-benchmark"

```

**Comment by duckyou** [comment]
@lk-geimfari https://github.com/duckyou/mimesis/tree/dev-performance

**Comment by lk-geimfari** [comment]
@duckyou Can you tell me, please, what is your operating system? I have some problem with `tox` on `Ubuntu 16.04` when `tox` tries to run tests on `Python 3.6`: https://gist.github.com/lk-geimfari/144ca2b0d19cf7f1fefee3c7df33dfde

**Comment by duckyou** [comment]
@lk-geimfari Here it is:
```bash
$ uname -osrv
Linux 4.9.73-1-MANJARO #1 SMP PREEMPT Fri Dec 29 17:58:25 UTC 2017 GNU/Linux
````
I understand your problem. `psutil` cant compile without python-dev libs. Have you installed `python3.6-dev`?
Here is full script which should work on `Ubuntu/Xenial`:
```bash
# Add python3.6 repo
#
sudo add-apt-repository -y ppa:jonathonf/python-3.6
sudo apt-get update

# Install tools
#
sudo apt-get -y install build-essential virtualenv git \
	python3-dev python3.6 python3.6-dev

# Setting up enviroment
#
git clone https://github.com/lk-geimfari/mimesis
cd mimesis/
virtualenv --python=python3.5 venv
source venv/bin/activate
pip install -r dev_requirements.txt
tox

```
