### ISSUE TITLE
Change current development workflow

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#351]
I have not seen the project in a while and have not contributed to it. I was confused about different tools and workflow this project uses:

1. `setup.py` commands
2. `Makefile`
3. `tox`
4. custom commands in CI

What do I suggest:
1. Stick to one thing only. It might be whatever we choose, but this tool should be the only possible way to do things
2. Update `Contributing.md`, since it does not contain any helpful information. What should be there? A step by step instruction how to do things. How to install dependencies? How to test your code? How to upload it to `pypi`?

**Comment by lk-geimfari** [comment]
@sobolevn I think that `tox` is overhead because we already use `Travis CI` which doing same things and even more.

About the second point: I'll updated file asap.

**Comment by duckyou** [comment]
@lk-geimfari But `tox` can run tests on several environments. It's very useful for a developer to final testing before push changes.

**Comment by lk-geimfari** [comment]
@duckyou I agree with you. But if we are creating the new branch for every new feature then `push` is not a problem I think. The code which works on Python 3.5 likely will work on Python 3.6.

We can vote what will be better if you want. 

Pros: Yes, it useful on some machines where does not installed both versions of Python.
Cons: It's duplicate functionality of Travis CI.

**Comment by lk-geimfari** [comment]
@sobolevn Your few words, please.

**Comment by duckyou** [comment]
@lk-geimfari Okay, you're right. It's unnecessary tool with travis and appveyor.

**Comment by sobolevn** [comment]
+1 for removing `tox`. It serves well when we need to test both `py2` and `py3`, but it is not so important when dealing with only two very similar versions of `python`.
