### ISSUE TITLE
PEP 257

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#361]
We should integrate some tool, which will check `__doc__` automatically. Your suggestions, gentlemen.

**Comment by lk-geimfari** [comment]
I like [pydocstyle](https://github.com/PyCQA/pydocstyle) which was suggested by @sobolevn. If there are no other proposals, we will use it.

**Comment by sobolevn** [comment]
`flake8-docstring` uses `pydocstyle` internally. It is just a wrapper to be used together with `flake8`.
