### ISSUE TITLE
Test all the methods of Generic

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#370]
At this moment we test only some methods:

```python
def test_generic_address(self, _generics):
    g1, g2 = _generics
    for _ in range(self.TIMES):
        assert g1.address.street_number() == g2.address.street_number()
        assert g1.address.street_name() == g2.address.street_name()
```

We should test all the methods of the attributes of Generic to be sure that all works fine.

Must be something like this:

```python
def test_generic_address_all(self, _generics):
    # Logic
    # Test all the methods of provider address dynamically.
```

**Comment by lk-geimfari** [comment]
@duckyou There are we need the same way which you're used in `benchamrks`, i.e something like this:

```python
@pytest.mark.parametrize(
    'method', (
        m for m in sorted(Provider.__dict__)
        if not m.startswith('_')
    ),
)
def test_method(method):
    # logic
```

**Comment by duckyou** [comment]
@lk-geimfari Test all methods of generic providers is not so necessary. This tests should check: will be seed argument passed to providers or not.

**Comment by lk-geimfari** [comment]
@duckyou I'll close this issue, but come back to it soon. 

We need to test all methods to be sure that all providers work correctly after adding to `Generic`.
