### ISSUE TITLE
I can't compile my project by pyinstaller

### ISSUE THREAD

**Issue by h0n3yc4k3** [lk-geimfari/mimesis#375]
I have a script with code:
```
from mimesis import Personal
person = Personal('en')
person.full_name()
```
and it works well, but after compiling this code to .exe via pyinstaller I have an error **FileNotFoundError: [Errno 2] No such file or directory: 'B:\\_MEI131682\\mimesis\\data/es\\personal.json'
[20624] Failed to execute script myproject**
So, I think that problem in path (`data/es\\personal`). What ways of solving this problem can you recommend?

**Comment by lk-geimfari** [comment]
@h0n3yc4k3 Seems like we have hardcoded path. It's a bug.

**Comment by lk-geimfari** [comment]
We need something like this:

```python
separator = '/' if sys.platform == 'linux' else '\'
file_path = path.join(DATA_DIR + '/' + locale_name, file)
```

**Comment by lk-geimfari** [comment]
@h0n3yc4k3 I have fixed this issue (see #376). Now, this should work fine. Can you, please, uninstall an old version (`v1.0.4`) of mimesis and install latest (`v1.0.5`) and confirm that issue was fixed. Thanks!

**Comment by h0n3yc4k3** [comment]
Yes, it fixed wrong path, but for unknown reasons pyinstaller doesnt import mimesis data :(

**Comment by lk-geimfari** [comment]
@h0n3yc4k3 Possible that the issue on the `pyinstaller` side. I really have not idea why this happens, sorry.

**Comment by h0n3yc4k3** [comment]
But I compiled it 😄 
I added mimesis data to working dir and executed `pyinstaller --onefile --add-data mimesis;mimesis myscript.py` and now all works fine :)

**Comment by lk-geimfari** [comment]
@h0n3yc4k3 My congratulations! That's awesome.
