### ISSUE TITLE
Adding industry-specific codes to a new "Industry" class.

### ISSUE THREAD

**Issue by dynamicwebpaige** [lk-geimfari/mimesis#377]
Many industrial fields (the petroleum industry, electrical engineering, chemical engineering, etc.) have industry specific codes and formatting that would be useful to generate synthetically.

**Examples**:
* [API well numbers](https://en.wikipedia.org/wiki/API_well_number) for exploratory wells - water, energy
* [Stock-Keeping Units](https://en.wikipedia.org/wiki/Stock_keeping_unit) (SKUs) and [Price Look-up Codes](https://en.wikipedia.org/wiki/Price_look-up_code) (PLCs)
* [Global Trade Item Numbers](https://en.wikipedia.org/wiki/Global_Trade_Item_Number)
* etc.

Is there interest to include these variations in an "Industry" class? Am open to changing the name! :)

Thanks,
pb

**Comment by lk-geimfari** [comment]
@dynamicwebpaige Sounds damn good! I like name `Industry`. It would be awesome to add such a data-provider. Do you want to add it by yourself?

**Comment by dynamicwebpaige** [comment]
You bet! :) Will go ahead and self-assign the issue.

**Comment by lk-geimfari** [comment]
Most of the data can be added to built-in providers, so there is no need in another one provider.
