### ISSUE TITLE
pypy support

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#381]
`pypy` has `python3.5` support. http://doc.pypy.org/en/latest/release-v5.10.1.html

So, maybe we can try to support that? 
It may give our users some performance increase.

Checklist:
- [ ] will it work
- [ ] does it require any changes
- [ ] add new travis/appveyor testing targets
- [ ] add `setup.py` classifier
- [ ] update docs

**Comment by lk-geimfari** [comment]
@sobolevn Literally yesterday I thought about the same thing.

**Comment by lk-geimfari** [comment]
@sobolevn So. I have tried to add support of `PyPy` and seems this is impossible (or almost), because: https://travis-ci.org/lk-geimfari/mimesis/jobs/331439757

**Comment by sobolevn** [comment]
Are ther any resources about typing and `pypy`? I have not touched `pypy` for several years now.

**Comment by lk-geimfari** [comment]
@sobolevn I have found almost nothing about using ones together.

**Comment by sobolevn** [comment]
Well, maybe we just have to wait. Should we close this issue?

**Comment by lk-geimfari** [comment]
@sobolevn Let's will leave it opened, maybe someone can work on this issue.

**Comment by duckyou** [comment]
@lk-geimfari Some time ago i also tested it with pypy3. It works, but mypy module not supported by pypy bcz cpython reasons like you say here https://github.com/lk-geimfari/mimesis/issues/381#issuecomment-359244973 0_o 
We can just skip mypy module in pipfile for pypy and ignore mypy tests. :bulb:

**Comment by lk-geimfari** [comment]
@duckyou How we can skip dependencies selectively? I mean, how we can skip mypy only on PyPY? Is there any way to remove mypy from Pipfile on the fly?

Something like this:

```
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then skip_mypy_here; fi
```

**Comment by sobolevn** [comment]
@lk-geimfari no, that's not possible.

**Comment by duckyou** [comment]
@lk-geimfari @sobolevn  Yes, like says here https://github.com/pypa/pipenv/issues/1334#issuecomment-359313432 we can filter deps:
```python
mypy = {version="*", platform_python_implementation="!='PyPy'"}
# or
mypy = {version="*", markers="platform_python_implementation != 'PyPy'"}
```
(Other supported markers we can find [here](https://github.com/pypa/pipenv/blob/f20583c36d3e8f372311aa47a15493fe3ccc35d3/pipenv/pep508checker.py#L28-L40), or read [PEP508 - Environment Markers](https://www.python.org/dev/peps/pep-0508/#environment-markers))

But! Heres problem... pypy3 cant work with `mypy` bcz `mypy` have in deps `typed-ast` which should be compile with cpython. And if we filter `mypy` in pipfile and lock it, its deps not be sub-filtered 😞

If we want fix this issue we should filter `mypy` with `typed-ast`, like:
```toml
mypy = {version="*", platform_python_implementation="!='PyPy'"}
typed-ast = {version=">=1.1.0,<1.2.0", platform_python_implementation="!='PyPy'"}
```
If you know more canonical solution, please, share with me 😺

**Comment by duckyou** [comment]
@lk-geimfari yes, its work! 

![screenshot_2018-01-22_12-02-17](https://user-images.githubusercontent.com/9839155/35212765-4739a624-ff6c-11e7-9c29-5be867351d56.png)
![screenshot_2018-01-22_12-05-19](https://user-images.githubusercontent.com/9839155/35212836-8a271e08-ff6c-11e7-8df6-90bad58bacff.png)

**Comment by lk-geimfari** [comment]
@duckyou Can you create PR, please?

**Comment by duckyou** [comment]
@sobolevn @lk-geimfari Appveyor don't have pypy3 enviroment 😞 Need write install script... but its so necessary tests it? PyPy3 really more faster than cpython in this situation? Maybe first benchmark it?)

**Comment by lk-geimfari** [comment]
@duckyou Sure. Better to benchmark it.

**Comment by duckyou** [comment]
💡 For speed increasing we can implement some functions with `C` or use `Cython`. But this decision excludes pypy support and maybe other exotic python implementations 🌵 Also may affect on windows supporting

**Comment by lk-geimfari** [comment]
@duckyou I think that at this moments this is overhead. But if we find a really slow solution we can try to optimize ones, including using `C`.

**Comment by lk-geimfari** [comment]
Here are many problems with PyPy. Let's close it and come back in next year :smile: .

**Comment by sobolevn** [comment]
Please, reconsider adding `Cython`. It may cause to many problems with building.
And provide a little performance gain.

**Comment by duckyou** [comment]
OK, les save it for dessert 😸
