### ISSUE TITLE
Generate geographic coordinates for country territory only

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#387]
When locale is specified it would be awesome to generate coordinates (`Address.coordinates`) only on the territory of the specified country.

**UPD:**

We can use [this](https://gist.github.com/lk-geimfari/0e5638302b00f299b39066223906e7d0) gist.

**Comment by lk-geimfari** [comment]
@duckyou Any ideas?

**Comment by pskalyber** [comment]
I we need it, we can use Google dataset here: https://developers.google.com/public-data/docs/canonical/countries_csv

**Comment by lk-geimfari** [comment]
The second question is should we add this feature only for supported locales or optionally, i.e like that:

```python
coordinates(country_code=Coordinates.RU)
```

**Comment by lk-geimfari** [comment]
@pskalyber Do you know how to use this ranges? I really don't know how to do it.

For example, we have coordinates of USA:
```
"US": {"lt": 37.09024, "lg": -95.712891}
```

How can we generate random `latitude` for USA? What's range should we use?
