### ISSUE TITLE
Added support of remote data

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#393]
Idia is very simple, just look at the code below:

```python
from mimesis.package import DataPackage

datapack = DataPackage(url='http://dataset.example/dir/dir/datapack.json')
data = datapack.get('super_data')

for item in data:
    # ...
```

This provider can be used extracting data from remote `.csv`, `.json` and `.zip` files.

**Comment by lk-geimfari** [comment]
I'm always open to suggestions and criticism.

**Comment by lk-geimfari** [comment]
@sobolevn @duckyou What do you think?

**Comment by lk-geimfari** [comment]
Datahub uses a similar way to get custom data: http://datahub.io/core/gold-prices#python

**Comment by sobolevn** [comment]
I would also make this a separate package.
Since it would require additional requirements:
- `requests`
- `caching`
- possibly some others

**Comment by lk-geimfari** [comment]
@sobolevn So, I'll close this issue, because we'll not add it to mimesis. I will try to implement this as a separate package in my spare time.
