### ISSUE TITLE
Use pyroma to validate package integrity

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#424]
There's a cool thing called [`pyroma`](https://github.com/regebro/pyroma).

It could prevent errors like #421 from happening.
I think we can use it. 

I will be happy to introduce a PR for this.

**Comment by lk-geimfari** [comment]
@sobolevn It would be awesome! Thanks!

**Comment by sobolevn** [comment]
Closed via https://github.com/lk-geimfari/mimesis/pull/429#issuecomment-376497204
