### ISSUE TITLE
Generate structured and non contradictory data

### ISSUE THREAD

**Issue by duckyou** [lk-geimfari/mimesis#430]
What if we implement something like this:

```python
>>> import json
>>> from mimesis.cards import PersonCard
>>> json.dumps(next(p), ident=4)
{
    "first_name": "Julio",
    "last_name": "Santos",
    "email": "juliosantos85@mail.com",
    "age": 33,
    "child_count": 3,
    "gender": "male",
    "work_experience": 11
    ...
}
```

Or upgrade schema provider to return non contradictory data. What do you think about this?

**Comment by lk-geimfari** [comment]
I think that it's partially duplicate `schema.Field`.

**Comment by lk-geimfari** [comment]
It's better to add good documentation about `schema.Field` to docs I think.

**Comment by duckyou** [comment]
@lk-geimfari Schema field can return contradict data. For example female first name and male second name.

**Comment by lk-geimfari** [comment]
@duckyou But you can use `**kwargs` for it.

```python
_ = Field('en')

name = _('name', gender=Gender.FEMALE)
surname = _('surname', gender=Gender.FEMALE)
```

**Comment by lk-geimfari** [comment]
There is no need to implement it in a core. A user can do it manually:

```python
random_gender = lambda: random.choice(list(Gender)) 
name = _('name', gender=random_gender())
```

**Comment by duckyou** [comment]
@lk-geimfari You goddamn right :bangbang: 
Also last questions: what about build-in schemas? Implement some schemas or omit it?

**Comment by lk-geimfari** [comment]
@duckyou I think that we should implement it as a third-party package, for example, named `mimesis-schemas`. I think that this is a compromise between the simplicity of the core and its capabilities.

```
from mimesis_schema import SomeCard
# ...
# ....
```

**Comment by lk-geimfari** [comment]
In core package, we need to improve existing features and fix bugs. It's our priority.

**Comment by duckyou** [comment]
@lk-geimfari you are reading my mind :wink: :+1:

**Comment by lk-geimfari** [comment]
@duckyou You can do it by yourself too. You're a member of `mimesis-lab`

Anyway, i have created repo for you: https://github.com/mimesis-lab/mimesis_schema

**Comment by sobolevn** [comment]
Nice! Closing.
