### ISSUE TITLE
Fix mypy issues

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#432]
There are several things to consider:

1. Fixing bugs like this one: https://travis-ci.org/lk-geimfari/mimesis/jobs/361128185#L600
2. Adding new options to `mypy` to make it stricter: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L67
3. Add `tests` folder to be checked by `mypy` (not only `mimesis/` folder is checked)

I can do it, if @lk-geimfari does not have anything to add/comment.

**Comment by lk-geimfari** [comment]
@sobolevn Sure!
