### ISSUE TITLE
Finally

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#437]
i think that it's better to use markdown.

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by sobolevn** [comment]
That will work only on new `pypi`. Let's wait until the old one is shut down.

**Comment by lk-geimfari** [comment]
@sobolevn Yeah. Seems that it will not work on legacy PyPi. So, i think that we'll continue use rst.
