### ISSUE TITLE
Do we really need to write type twice?

### ISSUE THREAD

**Issue by fried-sausage** [lk-geimfari/mimesis#458]
Example of duplicate type annotation: https://github.com/lk-geimfari/mimesis/blob/master/mimesis/helpers.py#L43

**Comment by lk-geimfari** [comment]
@fried-sausage Nope, actually, I just forgot to update docstrings for this method, sorry. Your PRs always welcome!

**Comment by lk-geimfari** [comment]
It's done in https://github.com/lk-geimfari/mimesis/commit/4a97010209b7f675e337538f9b6aacad6b6a244c.
