### ISSUE TITLE
Second, third and fourth level domains

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#466]
We can possible enhance `internet` provider to be able to generate fake domains like:
- `test.wemake.services`
- `mail.google.com`
- `app.test.example.com`
- `example.co.uk`
And others.

Link: https://en.wikipedia.org/wiki/Domain_name#Second-level_and_lower_level_domains

**Comment by lk-geimfari** [comment]
I'm all for it. I'll try work on it when I'll not busy.

**Comment by sadielbartholomew** [comment]
Hi, can I have a go at this if nobody else is working on it already?

**Comment by sadielbartholomew** [comment]
Perfect, thanks @lk-geimfari. I will attempt issue 484 first, but if nobody else has started to work on this by then I will try it.

**Comment by lk-geimfari** [comment]
@sadielbartholomew Great! Thank you!

**Comment by sadielbartholomew** [comment]
I've now had time to start implementing this; I'm working on it in [this branch](/sadielbartholomew/mimesis/tree/internet-lower-level-domains). Once it is complete, tested & documented I will put in a PR. Thanks again.

**Comment by lk-geimfari** [comment]
@sadielbartholomew Great news! Thank you for your time and for your interest! We'll wait for your PR.

**Comment by lk-geimfari** [comment]
@sadielbartholomew 🏓

**Comment by sadielbartholomew** [comment]
Sorry @lk-geimfari I am a bit busy at the moment but will get back onto this at the weekend. If I can't otherwise sort it I will post here so somebody else can take over (or do it their way).

**Comment by lk-geimfari** [comment]
@sadielbartholomew Sure! Thanks!

**Comment by sadielbartholomew** [comment]
*Update*: I am committed to completing this, but I am short for time so it will likely be mid-week before I can put in the corresponding PR. I will ensure I get it submitted before next Monday, however. Thanks for your patience.

**Comment by sobolevn** [comment]
@sadielbartholomew no pressure! Take your time.

**Comment by hvijaycse** [comment]
Hi, can I go for it if nobody else is working on it?

One thing I should only update the top_level_domain function, not the function which generates homepage right ??

**Comment by lk-geimfari** [comment]
@hvijaycse Feel free to work on it.

**Comment by terciero** [comment]
I'd love to give this a shot if no one else is currently working on it.

**Comment by lk-geimfari** [comment]
@terciero It would be great! Thank you!

**Comment by terciero** [comment]
Perfect! I'll pick up from the branch that @sadielbartholomew started.

**Comment by lk-geimfari** [comment]
Great! Thank you!

**Comment by terciero** [comment]
Slightly delayed by holidays, but still working on this!

**Comment by lk-geimfari** [comment]
@terciero 🏓

**Comment by terciero** [comment]
Have been away from an internet connection, but will be back on this
starting Monday.

If that is too much of a delay someone else can snag the issue.

**Comment by lk-geimfari** [comment]
This can be done, like this:
```
from mimesis import Internet

net = Internet()

net.hostname(subdomains=['one.two', 'one.two.tree'])

# Output: one.two.tree.marine.gov
```
