### ISSUE TITLE
Logo design for the application

### ISSUE THREAD

**Issue by richardbmx** [lk-geimfari/mimesis#474]
Hi, I see that you are requesting a [logo design for the application](https://opensourcedesign.net/jobs/jobs/2017-10-23-we-need-illustration-logo).  I am a graphic designer and I would like to make a logo for you if you wish..

Here you can see part of my work (https://steemit.com/@richardbmx)

**Comment by lk-geimfari** [comment]
Hi, Richard!

Thank you for your response, but it was an old request. We have already
updated our logo as you can see. If you interested, you can help us redraw
current our logo in the bigger resolution it would be awesome, but only if
you're interested. Thanks!

P.S You can find our current logo here:
https://github.com/lk-geimfari/mimesis
Let me know if you can do it.
