### ISSUE TITLE
Support hypothesis

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#475]
There's a `faker` plugin to support `hypothesis`. 
Sometimes I really need to generate some real-world values from `hypothesis` for some fields.
For example, there's a trouble with generating URLs for now.

So, we need to create a new library to integrate `mimesis` and `hypothesis` together, so I can use `mimesis` and not `faker` for these cases.

That's how it is currently implemented: https://github.com/HypothesisWorks/hypothesis/blob/01864efb809b1d4e9093bcc3a498ac4b30921047/hypothesis-python/src/hypothesis/extra/fakefactory.py

I have to mention that it is not considered a best practice, but it exists.

This issue should be closed after such package is publicly released.

**Comment by lucaswiman** [comment]
I built a simple wrapper that seems to work:
```python
def build_mimesis_strategy(mimesis_provider_class, method_name, *args, **kwargs):
    """
    Get an attribute from a mimesis provider by seeding with a hypothesis-chosen integer.
    """
    provider = mimesis_provider_class()

    def get_value(seed):
        provider.reseed(seed)
        return getattr(provider, method_name)(*args, **kwargs)

    return st.integers().map(get_value)
```

Then you can do the following:
```
>>> build_mimesis_strategy = st.build_mimesis_strategy
>>> states = build_mimesis_strategy(mimesis.Address, 'state', abbr=True)
>>> states.example()
'PA'
>>> states.example()
'TN'
>>> states.example()
'WV'
```
