### ISSUE TITLE
Unknown encoding

### ISSUE THREAD

**Issue by pimuzzo** [lk-geimfari/mimesis#479]
in https://github.com/lk-geimfari/mimesis/blob/master/mimesis/data/en/business.json and https://github.com/lk-geimfari/mimesis/blob/master/mimesis/data/en/address.json I've found:

```
"A�ropostale", -> Aéropostale
"Est�e Lauder Companies", -> Estée Lauder Companies
```

and

```
"La Ca�ada Flintridge", -> La Cañada Flintridge
```

**Comment by lk-geimfari** [comment]
@pimuzzo Can you create PR with a fix, please? Thanks!

**Comment by pimuzzo** [comment]
@lk-geimfari Sure!
