### ISSUE TITLE
elizabeth currently not available on pypi

### ISSUE THREAD

**Issue by t3chn0m4g3** [lk-geimfari/mimesis#488]
When trying to install `elizabeth` from pypi I am getting a `could not find error`. Searching for the packages reveals it is currently not available:
https://pypi.org/search/?q=elizabeth

**Comment by lk-geimfari** [comment]
@t3chn0m4g3 That right `elizabeth` is a deprecated and unmaintained package. You must use `mimesis`

**Comment by t3chn0m4g3** [comment]
@lk-geimfari Thanks for the swift response. I only realized this a few seconds after opening the ticket 😄
Thank you!

**Comment by lk-geimfari** [comment]
@t3chn0m4g3 Thank you for using this package! Have a nice day!
