### ISSUE TITLE
Use custom type for Optional

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#518]
We have a lot of code like this:

```
some_var: Optional[str] = None
```

Why we can't do it like this:

```
String = Optional[str]

sove_var: String = None
```

@sobolevn What do you think?

**Comment by sobolevn** [comment]
Nope, that's a bad idea. `Optional[str]` is very clear type. What is `String`? Mutable sequence of bytes? Immutable `str`? `Union[str, bytes, unicode]`?

**Comment by lk-geimfari** [comment]
@sobolevn Agree, looks not really good.
