### ISSUE TITLE
Test_utils.py fails

### ISSUE THREAD

**Issue by Valerievich** [lk-geimfari/mimesis#520]
I'm trying to `make test`. `python 3.7`
`test_download_image` fails every time.

There is an error:
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>`

**Comment by lk-geimfari** [comment]
@Valerievich Try this:  `download_image(url=url, unverified_ctx=True)`

**Comment by Valerievich** [comment]
It's a local problem. [This](https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore) resolution helped.
Now all the tests passed. Thank you.
