### ISSUE TITLE
Bug in [doctest] mimesis.utils.pull

### ISSUE THREAD

**Issue by Valerievich** [lk-geimfari/mimesis#523]
There is a bug in [doctest] mimesis.utils.pull:

```>>> en['day']['abbr'][0]
Expected:
    'Mon.'
Got:
    'Fri.'
```

**Comment by Valerievich** [comment]
I'm going to deal with it

**Comment by lk-geimfari** [comment]
@Valerievich Can you please add more information about how to reproduce this bug?

**Comment by Valerievich** [comment]
Sure! Just run `pytest --doctest-modules` and you'll see `DocTestFailure`

**Comment by Valerievich** [comment]
Can't start fixing this. My [PR](https://github.com/lk-geimfari/mimesis/pull/522) hasn't approved yet.

**Comment by lk-geimfari** [comment]
@Valerievich merged! You can start fixing this.

**Comment by Valerievich** [comment]
@lk-geimfari Since we've merged PR we could close this related issue.
