### ISSUE TITLE
Add support of time and date objects for Datetime

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#540]
We need to add support of `datetime.time` object for a method `Datetime.time` and `datetime.date` for `Datetime.date`.

- [ ] Add support of time object
- [ ] Add support of date object

Both methods should return an object (and string, but optionally), not just a string.

Currently, I'm working on v2.2.0 and we need to implement it in the branch `v2.2.0`

**Comment by potter-potter** [comment]
I'll grab this one.

**Comment by lk-geimfari** [comment]
Implemented in #539
