### ISSUE TITLE
Request for Indian locale addition

### ISSUE THREAD

**Issue by kuroop** [lk-geimfari/mimesis#560]
# Feature request

## Thesis

Addition of Indian locate. I saw that mimesis welcomes people to add new locales. I am assuming that what I need to do is:
1. Put locale data in https://github.com/lk-geimfari/mimesis/tree/master/mimesis/data following the given template. Not sure about the naming of it, either it would be en-IN or IN for Indian locale.
2. Writing unit tests for the newly added locale.

## Reasoning

I didn't find it and it will be useful for developers working with Indian users and need mimesis.

## Questions

1. Can I work on it. ( Not sure if it's already done )
2. What docs/resources I should go through.

**Comment by lk-geimfari** [comment]
@kuroop Answers:

Of course, you can!
Read this: https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst

**Comment by kuroop** [comment]
Hi @lk-geimfari ,

As a country, India has lot of languages. What is the criteria to select ? popularity? I would say both locales should be included; so can we plan for both? I personally would want to start with English(```en-in```) and probably pick up Hindi(```hi```) later on.

Thanks for the link to that CONTRIBUTING doc. I will go through it.

**Comment by lk-geimfari** [comment]
@kuroop Which locale is much popular? Which one will be much useful for developers?

**Comment by lk-geimfari** [comment]
Great, let's add only en-in.

вс, 4 нояб. 2018 г., 23:26 loki notifications@github.com:

**Comment by lk-geimfari** [comment]
There is no feedback, so I close this issue.
