### ISSUE TITLE
Add support of parameter unique for email, username and telephone.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#561]
# Feature request

## Thesis
This feature requested by @neumond

He propose to add parameter `unique` for `.email()`, `.username()` and `.telephone()` to make sure that they return only unique data while the provider's instance exists.

## Reasoning
Some fields must be unique and it would be a good idea to add support of parameter `unique` for such methods (`.email()`, `.username()` and `.telephone()`).

**Comment by jackhenry** [comment]
Hi @lk-geimfari 

I think this is a good idea and would be interested in implementing this.

One thing I want to mention is that during the life of the provider's instance there are a finite amount of unique values it could return. For example, when generating a ten digit phone number there are 10<sup>10</sup> unique possible phone numbers.

For ```.email()``` and ```.email()```, the amount of unique values is directly related to the amount of values in ```person.json```

Even though it's unlikely a single provider would be used to try to generate all possible unique values, should the implementation take into account that there are a finite amount of unique values possible for  ```.email()``` ```.username()``` and ```.telephone()```?
