### ISSUE TITLE
Different superclasses for different types of providers

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#565]
## Thesis

The providers which have locale dependent must be inherited from `BaseDataProvider`, but providers which just works with standard data structures, without storing data in JSON from `BaseProvider`.

## Reasoning
Locale independent providers must not contain any attributes of providers which has locale dependent. It can help make API much clear without the chaos of inheritance.

**Comment by lk-geimfari** [comment]
@sobolevn What do you think? We don't need attribute `self.locale` in locale independent provider anyway.

**Comment by sobolevn** [comment]
Seems like a plan!
