### ISSUE TITLE
Moving utils.pull to BaseDataProvider

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#568]
# Feature request

## Thesis
I suggest moving `utils.pull` to `BaseDataProvider` because it's only needed for locale-dependent providers, which are all subclasses of `BaseDataProvider`.

## Reasoning
We are forced to always manually import `pull` to the modules where are we create new providers and repeat the same code, although the pull is needed only for locale-dependent providers which are all inherited from `BaseDataProvider`. It will be much logically correct to keep pull in provider `BaseDataProvider` I think.

The idea is simple, instead of this:
```python
from mimesis.utils import pull

class OldProvider(BaseDataProvider):

    def __init__(self, *args, **kwargs):
        """Initialize attributes.
        """
        super().__init__(*args, **kwargs)
        self._datafile = 'datetime.json'
        self._data = pull(self._datafile, self.locale)
```

Use this:

```python
class NewProvider(BaseDataProvider):

    def __init__(self, *args, **kwargs):
        """Initialize attributes.
        """
        super().__init__(*args, **kwargs)
        self._datafile = 'datetime.json'
        self.pull(self._datafile)
```
After this we'll able to use pull withot any extra importing.

That's just discussion, I have not started working on this yet.

**Comment by sobolevn** [comment]
@lk-geimfari I agree. I think that all modules that start with `util` are just not placed well in some other entities. Related: https://wemake-python-styleguide.readthedocs.io/en/latest/pages/violations/naming.html#wemake_python_styleguide.violations.naming.WrongModuleNameViolation

So, maybe we can refactor the whole module?

**Comment by lk-geimfari** [comment]
@sobolevn Yeah, I think about it too. This release will contain breaking things anyway (because there was too much really old and bad solution inherited from the very early version of the `church`). Any possible breaking features must be implemented here, in v3.0.0. 

Create an issue for it, please.

**Comment by lk-geimfari** [comment]
I also suggest renaming other internal modules with bad names, such as `helpers`, `__version__`

**Comment by lk-geimfari** [comment]
Done.
