### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by pimuzzo** [lk-geimfari/mimesis#585]
hello, is it possible to have a new release? thank you

**Comment by lk-geimfari** [comment]
@pimuzzo We have planned too many changes and the new release will be published only at December, because of work still in progress.

**Comment by pimuzzo** [comment]
Thank you for your fast reply :)

**Comment by lk-geimfari** [comment]
@pimuzzo Hey! I am glad to inform you that we have published version 3.0.0. Please, carefully read the changelog before installing the new version because there are breaking changes in API. Thanks!

Changelog available [here](https://mimesis.readthedocs.io/changelog.html).
