### ISSUE TITLE
Build failure on Windows (PYTHON_ARCH=32)

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#587]
Seems like error happens because of memory error.

Details:
https://ci.appveyor.com/project/lk-geimfari/mimesis/builds/20546900/job/it885ivv7m2usk60

This issue must be fixed.

**Comment by lk-geimfari** [comment]
@duckyou Do you have any idea why it happens?

**Comment by duckyou** [comment]
@lk-geimfari , sorry, i have no idea why this happened
From official documentations, this may be explained with runs out of memory.
https://docs.python.org/3/library/exceptions.html#MemoryError
You already fix this problem?

**Comment by lk-geimfari** [comment]
@duckyou Okay, thanks! I'll check it.
