### ISSUE TITLE
Use wemake-python-styleguide

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#598]
Can we use `wemake-python-styleguide` for mimesis?

@sobolevn What do you think?

**Comment by sobolevn** [comment]
It will require the complete refactoring. But, it would be interesting experience for me.
Since, I have not tried to integrate this linter to some existing code bases. 

Only new ones.

**Comment by lk-geimfari** [comment]
There might be too many changes. I temporarily close it.
