### ISSUE TITLE
Enforce HTTPS for mimesis.name

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#601]
Recently I've bought domain [mimesis.name](http://mimesis.name/getting_started.html), but at this moment It works on HTTP,  not HTTPS. We need to fix it (ReadTheDocs allows SSL on custom domains)

Related:
* [Custom Domain SSL](https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-ssl)
* [Certification Authority Authorization (CAA) FAQ](https://support.cloudflare.com/hc/en-us/articles/115000310832-Certification-Authority-Authorization-CAA-FAQ)

@sobolevn I have really small experience in such things, so I've granted you access to Namecheap and ReadTheDocs. I hope you can find a minute to look at this issue. Thanks.

**Comment by sobolevn** [comment]
Sure, but a little bit latter. Nice domain! Grats!

**Comment by lk-geimfari** [comment]
Seems like I've fixed it. I just remove custom domain from read the docs admin and add it again, so now we have `https`: https://mimesis.name/. That's cool.
