### ISSUE TITLE
Hardcoded parameters used for random.randint() in Person.username()

### ISSUE THREAD

**Issue by jackhenry** [lk-geimfari/mimesis#609]
Looking at the ```username()``` function in ```providers/person.py``` I found this line:

```
date = self.random.randint(1800, 2070)
```

@lk-geimfari Do you know why these parameters are hardcoded? For #561, I need to calculate all the possible unique combinations the ```username()``` function can return and I want to avoid hardcoding any numbers in the formula I use. If this range of random integers gets changed in the future, it will break my implementation.

**Comment by lk-geimfari** [comment]
You can change it if you want.
