### ISSUE TITLE
Make mimesis PEP561 compatible

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#642]
What is PEP561? https://www.python.org/dev/peps/pep-0561/

It is a way to ship types together with the code itself.
If the package is PEP561 compatible, then `mypy` will import types from it and use it together with user defined ones. Otherwise, everything will be `Any`.

So, our end-users might benefit from using our library with `mypy`.

What needs to be done?
- [x] Create `py.typed` file: https://github.com/dry-python/returns/blob/master/returns/py.typed
- [x] Make sure it is bundled together with other python files

**Comment by lk-geimfari** [comment]
I think that we need to include it in MANIFEST, need we?

**Comment by sobolevn** [comment]
I guess so, I have never done it with `MANIFEST`s, `poetry` handles all these things for me: https://github.com/dry-python/returns/blob/master/pyproject.toml

**Comment by lk-geimfari** [comment]
I have included it to package in `MANIFEST.in`

**Comment by sobolevn** [comment]
@lk-geimfari can you verify that this file is included into the final tarball?

**Comment by lk-geimfari** [comment]
@sobolevn Yeah, it is.

**Comment by sobolevn** [comment]
Then we can close this issue. Thanks a lot!
