### ISSUE TITLE
Refactor issue templates

### ISSUE THREAD

**Issue by sobolevn** [lk-geimfari/mimesis#644]
Create issue page is misleading: 
<img width="784" alt="2019-03-01 12 28 16" src="https://user-images.githubusercontent.com/4660275/53629325-538dd400-3c1e-11e9-802c-8b809fc065fc.png">

What is this "Custom template"? I am not sure that this is a good DX.
And I propose to rename it.

**Comment by lk-geimfari** [comment]
I agree it's better to remove it.
