### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#647]
We're looking for people who want to work on mimesis with us. At this moment this package is maintained only by @sobolevn and me (@lk-geimfari ). 

The problem is that we are both busy а lot of time and we need third and fourth pilots.

What will you have to do?

1. Code review
2. Bug fix
3. Adding new cool features
4. Releasing new versions

We need new collaborators to always keep mimesis up-to-date when someone of us is busy.

**Comment by ceccoemi** [comment]
Hi,

I like this project and I will glad to be a collaborator if you need. 

I have recently did a couples of pull requests (like [this](https://github.com/lk-geimfari/mimesis/pull/640)) so I have already get the logic behind this package.

Please, let me know.

**Comment by lk-geimfari** [comment]
@ceccoemi I have invited you to our organization. I'll also add you to collaborators when we will see that you completely understand our standards and goals.

**Comment by lk-geimfari** [comment]
It's done. @ceccoemi will be with us.
