### ISSUE TITLE
Datetime ranges using datetime.datetime

### ISSUE THREAD

**Issue by eljfe** [lk-geimfari/mimesis#653]
# Feature request

datetime.datetime support in Datetime class objects (that sounds funny :-)

## Thesis

Dates are fussy.  More granular options makes for better test data:

take this:

`formatted_datetime(fmt='%Y-%m-%d %H:%M:%S.%f', start=2018, end=2019)`

and make it something like this:

`formatted_datetime(fmt='%Y-%m-%d %H:%M:%S.%f', start=datetime(2018, 10, 9, 8, 7, 6, 543210) , end=datetime.now())`

## Reasoning

Some of my tests evaluate timestamps.  My test data should run from now into the past.  

Thanks!

**Comment by lk-geimfari** [comment]
@eljfe Hi! First of all thanks for your interest.

We have created a much detailed mechanism for generating datetime objects by range. Can you, please check out function `bulk_create_datetimes ()` of provider `Datetime`.

It generates a range of datetime objects and you can pass to it all the arguments you can pass to `timedelta ` from the standard library.

Is it suit for your case?

**Comment by eljfe** [comment]
Hi Likio. 
Appreciate your prompt response! I shall look into the bulk method you mentioned. 

Best and thanks again,
Jeff
