### ISSUE TITLE
Auto add builtin provider to Generic based on passed locale

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#674]
# Feature request

An idea is very simple:

```python
generic = Generic('ru', auto_add_builtin=True)
generic.russia_provider.inn()
```

Instead of this:

```python
from mimesis import Generic
from mimesis.builtins import RussiaSpecProvider

generic = Generic('ru')
generic.add_provider(RussiaSpecProvider)
generic.russia_provider.inn()
```

Optionally we can make builtin's name customizable: 

```python
generic = Generic('ru', auto_add_builtin=True, builtin_custom_name='russia')
generic.russia.inn()
```

**Comment by lk-geimfari** [comment]
@ceccoemi @sobolevn What do you, guys, think?

**Comment by sobolevn** [comment]
I do not see any problems with this three lines of code.
What problem are you trying to solve?

**Comment by lk-geimfari** [comment]
@sobolevn I'm trying to make it easier to add country-specific data to Generic. For example, in common cases when you need to generate Personal info for locale `ru`, you will exactly need some data from `RussiaSpecProvider`, such as `inn`, `patronymic` and etc.

**Comment by ceccoemi** [comment]
@lk-geimfari I think that is a good idea.

What do you think about adding the builtin provider by default? The generic provider generates all the data from a locale so I think that is reasonable to add the builtin too:

    g = Generic('ru')
    g.russia_provider.inn()

It's ok to add the parameter `builtin_custom_name` if you think that it will not add unnecessary complexity.

I could work on this next week. Let me know!
