### ISSUE TITLE
How to link schemas?

### ISSUE THREAD

**Issue by ivan98** [lk-geimfari/mimesis#683]
I need to generate sample data for a normalized data structure, and I'm not sure how to do it efficiently in Mimesis. Would appreciate pointers in the right direction for me. Thanks.

Let's say I have
- an entity called Person, with a primary key of id.
- an entity called Email Account, with a primary key of email-address.
- an entity called Email, with a primary key of message-id.

__Primary key/Foreign key links__
A Person can have 0 or more Email Accounts.
An Email Account can have 0 or more Emails.

At the end of the day, I would like to dump all the test data for the 3 entities into 3 DB tables, or 3 CSV files, that can be reconstructed in the future, using the links between the 3 entities.

**Comment by lk-geimfari** [comment]
I'm afraid that this is not the task that `Schema` solves. You better to use common providers for your case. Problems you described must be solved on the ORM level if I understand you correctly.

**Comment by lk-geimfari** [comment]
@sobolevn @ceccoemi Any additions?

**Comment by sobolevn** [comment]
You can use https://github.com/mimesis-lab/mimesis-factory

**Comment by lk-geimfari** [comment]
I'm closing this issue, but if you have more questions feel free to reopen it.
