### ISSUE TITLE
Country generation does not respect chosen locale

### ISSUE THREAD

**Issue by andkii** [lk-geimfari/mimesis#696]
It appears that `Address('en').country()` does not respect the locale. Countries outside locale are still generated. 

Looking at the code it appears there is no implementation for locale specific country, if so, please change issue to a feature request.

**Comment by lk-geimfari** [comment]
Can you explain, please, what do you exactly expect? `.country()` returns name of the country for the current locale.

For example:

```
address = Address('ru')

address.country()
'Китай'

address.country()
'Россия'
```

Do you expect something like this?
```
address = Address('en')

address.country()
'United States of America'

address.country()
'United States of America'
```

**Comment by andkii** [comment]
Yes my understanding was that it would return a country who belongs to the locale. Now I can see that it is not the case and it is intended to be that way. Thanks.

Nevertheless locale specific data would be a great feature

**Comment by lk-geimfari** [comment]
@andkii We will fix it ASAP. By default, it must return the name of the current country.

We can just add a parameter `allow_random` which will allow random values for it.

@ceccoemi If my memory doesn't let me down, you've already done something like this, haven't you?

**Comment by ceccoemi** [comment]
Yes, we did the same thing in #664

I will work on it!

**Comment by lk-geimfari** [comment]
Great! Thanks!

**Comment by ceccoemi** [comment]
@lk-geimfari what do you think about doing the same thing with the `continent()` function?

**Comment by lk-geimfari** [comment]
@ceccoemi I thinks it's can be useful.

**Comment by ceccoemi** [comment]
@lk-geimfari no, maybe it's better to leave it as it is. Because some countries don't have a single specific continent, for example Russia and Turkey, they belong both to Europa and Asia. It could be ambiguous in some  situations.

**Comment by lk-geimfari** [comment]
@ceccoemi Agree. Let's don't change it.
