### ISSUE TITLE
Using Black for code formatting

### ISSUE THREAD

**Issue by ceccoemi** [lk-geimfari/mimesis#699]
# Feature request

## Thesis

I recently discovered [Black](https://github.com/python/black). It is an easy to use and fast code formatter built specific for Python. I think that could be great and very simple to introduce it in mimesis

## Reasoning

Since a main focus of this package is to have a good code quality, I think that should be a great thing to introduce a code formatter in order to have a standard to follow when writing code.

Black proposes a code style that is very similar to the one that we are using. However, the only thing that I don't like about Black is that, by default, it sets the line length to 88, but it is customizable with a `pyproject.toml` file and we can set it to 80 (which I personally prefer).

See the README of Black for more info or, if you have more time, watch [this talk](https://www.youtube.com/watch?v=esZLCuWs_2Y) for an introduction to this package. 

If you like Black, I would happy to integrate it in mimesis.

**Comment by lk-geimfari** [comment]
@ceccoemi The only thing I do not like in `Black` is `"string"` instead of `'string'`. I'm totally sure that @sobolevn has interesting thoughts about it.

**Comment by lk-geimfari** [comment]
So, if @sobolevn don't mind, I don't mind too.

**Comment by sobolevn** [comment]
Not on my watch! https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/integrations.html#black
