### ISSUE TITLE
Update data for locale ru

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#712]
# Feature request

We need to update data for locale `ru`. We can update all JSON files.

- text.json
- person.json

**Comment by obulat** [comment]
What exactly needs to be updated in these files? I'd like to try to tackle this issue for Hacktoberfest.

**Comment by lk-geimfari** [comment]
@obulat Thanks for the interest, but I'll resolve this issue by myself, it's too long to explain. You can take another issue. Thanks!

**Comment by lk-geimfari** [comment]
But If you really really want to do this: We need to check all datafiles for locale `ru` to find and delete incorrect data or to extend existing data if there are too little data.

Data for locale `ru` located here: `mimesis/data/ru/`

**Comment by LilJohny** [comment]
@lk-geimfari Can I do this?

**Comment by lk-geimfari** [comment]
@LilJohny Sure.

**Comment by LilJohny** [comment]
@lk-geimfari  Please check my pull request #740
