### ISSUE TITLE
Add maximum size parameter in text and names data

### ISSUE THREAD

**Issue by LucianoAlzugaray** [lk-geimfari/mimesis#713]
I think that the data needs a maximun size to, probably, be used to a test with maximum size on the text or strings fields.

This can be a parameter in string fields, like  

```python
> from mimesis import Person
> person = Person('en')
> person.full_name()
'Dominick Christian' 
> person.full_name(max_size=15) #Now limit the output size
'Marshall Cherry' #15 chars
> person.full_name(max_size=15)
'Emerita Cain' # 12 chars
> person.full_name(max_size=15)
'Brittni Webster' # 14 chars
> person.full_name(max_size=15)
'Demarcus Klein' #14 chars
```
This can be achieved in every string random data.

I thought this feature using this module in a database. I had a factory to generate objects with random data in the fields. I used this factory in a test suite to test the application in a more realistic way. This factory built objects based in a model to de database, so the data had some constraints, like the max chars size in the string and texts fields. When I run the tests, sometimes failed, only because the random data requested is larger than the model data attribute. With this improvement, a developer can use the module without worry if the data has the correct size.

The string data type is the one that can vary the most in terms of size, and controlling it would be a great feature.

**Comment by lk-geimfari** [comment]
Unfortunately, it's not that easy as it can look. This feature will generate data much slower.

I only can recommend to inherit provider you need and override function, like this:
```python
class CustomPerson(mimesis.Person):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def full_name(self, max_size: int = None, *args, **kwargs):
        # Override it here
```

or you can create PR with your implementation and we can look at the result and understand could we merge it.

@sobolevn @ceccoemi Do you have any comments or additions, guys?

**Comment by LucianoAlzugaray** [comment]
I think that considering this characteristic is important since two of the most frequent uses are probably the generation of random data for testing and database population. 

I'm thinking of sending a PR, where when you instantiate the object that has string-like data with an argument like 
`
> from mimesis import Person
> person = Person('en', limit_string = True) 
`
generate an indexing like database style. I think that with a algorithm a little thought you can generate this PR with a low loss of performance, and make optional the use of this algorithm.
