### ISSUE TITLE
Publish package on Anaconda Repository Index.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#722]
Mimesis can be extremely useful when you use it with Jupyter Notebook.

**Comment by Shanmugapriya03** [comment]
Python packages can be installed in Jupyter notebook by adding a prefix `!` to pip install command
`! pip install mimesis`

**Comment by lk-geimfari** [comment]
@Shanmugapriya03 Oh, great! I didn't know it. It would be great to add this information to docs.

**Comment by Shanmugapriya03** [comment]
Will add it in docs 😄
