### ISSUE TITLE
Tests fails on locale fa sometimes.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#725]
Sometimes tests fail on testing locale `fa`. We need to figure out why it happens and fix it.

**Comment by armonge** [comment]
Any reproduction steps? i'm currently running `LANG=fa LOCALE=fa pipenv run pytest  --cov=mimesis` and i can't reproduce it

**Comment by lk-geimfari** [comment]
@armonge Sure: https://travis-ci.org/lk-geimfari/mimesis/jobs/540850369

**Comment by tadashigaki** [comment]
Needed two `|` in each line, but  here is only one `|`. Fixing now. 

https://github.com/lk-geimfari/mimesis/blob/043d8d8fb6f49daf7afeeeafe4caa87d4420f266/mimesis/data/fa/science.json#L19

**Comment by lk-geimfari** [comment]
@tadashigaki Great work! Thank you!
