### ISSUE TITLE
The matrix generators for provider Numbers()

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#727]
# Feature request

## Thesis
The matrix can be useful in working in Jupyter Notebook. So, it would be awesome to support generators of matrix in provider `Numbers()`.

I sketched a rough implementation example:

```python
import random

from typing import Tuple, Optional, Union, List

ValuesRange = Union[
    List[int],
    Tuple[int, int],
]


def matrix(m: int = 3, n: int = 3, values_range: Optional[ValuesRange] = None) -> list:
    """Creates an 𝑚×𝑛 matrix which has 𝑚 rows and 𝑛 columns.

    :param m: Rows count.
    :param n: Columns count.
    :param values_range: Range of values of matrix items.
    :return: Matrix 𝑚×𝑛.
    """
    if values_range is None:
        values_range = (-100, 100)

    if len(values_range) > 2:
        raise ValueError('Invalid items range! Usage example: items_range=(-10, 10)')

    result = [
        [random.randint(*values_range) for _ in range(m)]
        for _ in range(n)
    ]

    return result

matrix(m=5, n=4, values_range=[-50, 50])
```

Output:
```python
[[29, 7, 17, -24, -29],
 [-26, 13, 29, -25, 6],
 [-5, 16, 13, -45, 49],
 [23, 20, -25, 14, -25]]
```

**Comment by anshulxyz** [comment]
hi @lk-geimfari I'd like to work on this?

**Comment by lk-geimfari** [comment]
@anshulxyz Great! Don't forget to read `CONTRIBUTING.rst`.

Current implementation won't work when m or n is equal to 0. You need to check this out too.

Thanks and happy hacking!

**Comment by anshulxyz** [comment]
Awesome! Can you assign this issue to me here: 

![Screenshot from 2019-10-01 13-22-16](https://user-images.githubusercontent.com/6121530/65944079-916e0780-e44e-11e9-8e39-7c98e93d39ba.png)

That would help me in finding all the issues assigned to me.

Also anything else I should know before starting?

**Comment by lk-geimfari** [comment]
@anshulxyz Done! That's it. Just read this: https://mimesis.readthedocs.io/contributing.html

**Comment by lk-geimfari** [comment]
@anshulxyz Also, provider `Numbers()` is located here: https://github.com/lk-geimfari/mimesis/blob/master/mimesis/providers/numbers.py

**Comment by lk-geimfari** [comment]
I have unassigned this issue because of a lack of any activity in 10 days. So, anyone can take this issue for Hacktoberfest.

**Comment by LilJohny** [comment]
@lk-geimfari  Can I take this?

**Comment by lk-geimfari** [comment]
@LilJohny Sure you can. Feel free to create PR. You can also create a method for generating tensors.

**Comment by gupta-kartik20** [comment]
@lk-geimfari Hi! I'd like to work on it. Kindly allow me an issue here.

**Comment by lk-geimfari** [comment]
@gupta-kartik20 Sure! I'll wait for PR.
