### ISSUE TITLE
CI pip dependency cache may be stale

### ISSUE THREAD

**Issue by jwilges** [lk-geimfari/mimesis#759]
# CI build error

## What's wrong

It looks like all [recent](https://travis-ci.org/lk-geimfari/mimesis/builds/614763358) Travis CI builds are failing in part due to the `mypy-extensions` package (0.4.2) failing a hash check. I noticed this in the [build results for my recent patch request](https://travis-ci.org/lk-geimfari/mimesis/jobs/614828210#L493):

```
[pipenv.exceptions.InstallError]: ['Collecting mypy-extensions==0.4.2 (from -r /tmp/pipenv-b9jw2c5s-requirements/pipenv-bt98vvy2-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/55/aa/2df16f9c6215b10c472fd7564b5f2c5644c13ab9c26d83b1c9373c11d97d/mypy_extensions-0.4.2-py2.py3-none-any.whl']
[pipenv.exceptions.InstallError]: ['THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.', '    mypy-extensions==0.4.2 from https://files.pythonhosted.org/packages/55/aa/2df16f9c6215b10c472fd7564b5f2c5644c13ab9c26d83b1c9373c11d97d/mypy_extensions-0.4.2-py2.py3-none-any.whl#sha256=c77e34350c01523cd63b6dc30b36515107b2c3cbacc8392d51d33ea18d59f8f1 (from -r /tmp/pipenv-b9jw2c5s-requirements/pipenv-bt98vvy2-requirement.txt (line 1)):', '        Expected sha256 a161e3b917053de87dbe469987e173e49fb454eca10ef28b48b384538cc11458', '             Got        c77e34350c01523cd63b6dc30b36515107b2c3cbacc8392d51d33ea18d59f8f1']
```

(output trimmed for brevity and to focus on the point)

I have not investigated if this is due to `mimesis` CI builds using an incorrect strategy when storing relevant cache keys (i.e. not noticing an update to this package) or if it is a stale `Pipfile.lock` value, but I suspect it is one of those and/or that perhaps `mypy-extensions` republished a package without bumping their package version. It may be worth bumping the requirement to `mypy-extensions~=0.4.3` if it was a republished package snafu.

As a first step, the cache key should be bumped to trigger caching the latest package contents from the Python package index. If nobody else has the bandwidth to look into that, I can make a separate pull request to address it.

## How it should be

The CI builds should not fail due to a stale pip dependency cache.

## System information

This occurs during the project's Travis CI builds.

**Comment by lk-geimfari** [comment]
@jwilges First of all, thank you! It would be really great if you can create PR. I'm too busy unfortunately and I can't work on it right now, but I can merge PR — it not takes much time.

**Comment by jwilges** [comment]
Thanks, @lk-geimfari and @ceccoemi.

I'll take a look at the remaining build issue for Windows 10 as it's also likely a fairly quick fix.
