### ISSUE TITLE
Improve IPv4/IPv6 generators for Internet()

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#761]
We can improve how `.ip_v4()` and `.ip_v6()` works.

I suggest using `ipaddress` module from the standard library, just like this:

```python
    def ip_v4(self, with_port: bool = False, stringify: bool = True) -> Union[str, IPv4Address]:
        """Generate a random IPv4 address.

        :param stringify:  Return IPv4 as string (True by default).
        :param with_port: Add port to IP.
        :return: Random IPv4 address.

        :Example:
            19.121.223.58
        """
        ipv4 = IPv4Address(self.random.getrandbits(32))

        if not stringify:
            return ipv4

        if with_port:
            ipv4 += ':{}'.format(self.port())

        return ipv4
```

The idea is to support IP addresses as objects to make them more useful than just strings.

**Comment by TacoBel42** [comment]
I can make class with methods like: 
• .get_mask() 
• .set_public()
• .set_local() 
• .add_DN() - Domain name 
• .set_route() 
• .add_to_route_list() 

Give me response about my idea

**Comment by lk-geimfari** [comment]
Done! #780
