### ISSUE TITLE
Restructure Numbers provider

### ISSUE THREAD

**Issue by ceccoemi** [lk-geimfari/mimesis#769]
# Feature request

## Thesis

While I was implementing the ``matrix()`` function in the ``Numbers`` provider and I was thinking about some changes that we could make in this provider:

- Add a function ``complex(start, end, length)`` that return a random array of complex numbers
- Make the API uniform, so that every function in the ``Numbers`` provider has the arguments ``start, end, length`` (where possible). Maybe in the ``complex()`` function we can add ``start_real, end_real, start_imaginary, end_imaginary`` ?
- Remove the function ``ranting()`` and add an argument ``decimal_digits`` in the function ``floats()`` to specify the number of decimal digits to keep.

## Reasoning

I think these changes would make the provider more uniform and easy to use.

**Comment by lk-geimfari** [comment]
@ceccoemi I like this idea. You can implement it. Please, try to do changes without broking API.

**Comment by lk-geimfari** [comment]
@ceccoemi And yeah you're right — `rating` is not really useful function. Just do not forget about changelogs and inform there what users must use instead of it. Thank you!
