### ISSUE TITLE
Tests failing on Python 3.8

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#771]
Seems like tests are failed on Python 3.8 like we can see here: #770. We need to fix it.

As I can judge it happens because of the enum object. Not sure why exactly, but it seems it's related to it: https://travis-ci.org/lk-geimfari/mimesis/jobs/619191162?utm_medium=notification&utm_source=github_status

**Comment by ceccoemi** [comment]
Found the issue!
If you run in a Python 3.7 prompt


    >>> 'nill' in mimesis.enums.PortRange


you get the warning

    DeprecationWarning: using non-Enums in containment checks will raise TypeError in Python 3.8

I will fix the issue

**Comment by lk-geimfari** [comment]
@ceccoemi Well, now tests fails only on Windows. Much better, but we also need to fix the issue with Windows too (but the problem with Windows is unrelated to this issue).

**Comment by lk-geimfari** [comment]
Fixed in #774
