### ISSUE TITLE
How to restrict the length of string generated 

### ISSUE THREAD

**Issue by harshabugg** [lk-geimfari/mimesis#794]
If I am generating username in the following way
generic.person.username('UU_d')
How can I restrict the length of string generated to say only 8 characters or 10 characters?

**Comment by lk-geimfari** [comment]
I'm afraid that you need to cut them using slice because at this moment there is no such feature.

Like this:
```python
person = Person('en')
person.username()[:8]
```

The problem here that it can generate usernames with length of of less than 8 characters.

**Comment by harshabugg** [comment]
Thank you. 

Is it possible to add this feature and make a release as I feel this feature would be really helpful?

**Comment by lk-geimfari** [comment]
I think we can add something like this:

```python
person.username(max_length=8)
'UserName'
```

So, my answer is yes we will add such a feature. The release of 4.0.0 will be not really soon but we will add such a feature to it.

Thank you for your interest and suggestion we appreciate it.

**Comment by harshabugg** [comment]
Thanks for your support.

**Comment by ceccoemi** [comment]
@lk-geimfari with the current implementation, I think that is a bit complicated to generate usernames of a given length or of a certain maximum length. There are too much variables such as the chosen template and the number of digits. To implement this feature, I think that this method needs to be changed

**Comment by lk-geimfari** [comment]
@ceccoemi I have tried today and yes, you're totally right. It's too complicated. I don't think the effort is worth it.
