### ISSUE TITLE
Update swiss person dataset

### ISSUE THREAD

**Issue by jrast** [lk-geimfari/mimesis#835]
The swiss (de-ch) person dataset seems to have quite untypical names (first names) in it. Also the list of last names is quite short. 

The Federal Statistical Office has a large list with firstnames and how common they are (where in 2018): [Source](https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/geburten-todesfaelle/vornamen-schweiz.html)

The swiss post provides a large collection about the last names: [opendata.swiss](https://opendata.swiss/de/dataset/nachnamen-pro-plz), [swisspost](https://swisspost.opendatasoft.com/explore/dataset/nachnamen_proplz)

Should I create a pull request with adjusted lists for this data? If so, how many names to include for first names (women / man) and last names? Should I use the most commonly used or a random sample?

**Comment by lk-geimfari** [comment]
Great idea! I think 8k names (or less) and 8k  (or less) surnames will be enough. The main condition is that names must be valid and that's it.

I'll be waiting for your PR.
