### ISSUE TITLE
Outdated “current” year

### ISSUE THREAD

**Issue by eumiro** [lk-geimfari/mimesis#870]
# Bug report

## What's wrong

Some providers return “current” dates from a few years ago, because they are hardwired to the “current” year from those times, such as:

- `mimesis.Datetime().week_date()`
- `mimesis.Datetime().date()`
- `mimesis.Development().version(calver=True)`
- `PolandSpecProvider().pesel()`

## How is that should be

Having a global `now` would break a lot of things, because with the same `seed`, we would get different results at each run.

Then maybe changing mimesis' versioning to calver and do such updates of default year with every major version? This would allow adding methods like `birthdate` to the `Person` provider as well.

## System information

Not relevant.

**Comment by lk-geimfari** [comment]
@eumiro I think that we need to make `end` parameter equal to `None` and use `datetime.now` when `end` was not passed.

**Comment by eumiro** [comment]
This would break the logic. Every time you initialize `mimesis` with the same seed and call the method with `None`, it will deliver different results.

**Comment by lk-geimfari** [comment]
Right, but it will break thing if we will to it like this too:

```
Then maybe changing mimesis' versioning to calver and do such updates of default year with every major version? This would allow adding methods like birthdate to the Person provider as well.
```

**Comment by lk-geimfari** [comment]
@sobolevn @ceccoemi Any suggestions?

**Comment by lk-geimfari** [comment]
@eumiro What if you pass parameters `start` and `end` explicitly?

**Comment by eumiro** [comment]
> @eumiro What if you pass parameters `start` and `end` explicitly?

In that case it works as imagined, of course. The question is, how much code you want to let the user write.

There could be some global switch between deterministic (hardwired minimal and maximal year) and more realistic behavior (`datetime.utcnow`). Now the only realistic external factor is the clock, but mimesis could read and use the current locale (possible) or get the current location to generate random locations in the neighborhood (okay, this is already exaggerated but works as an example).

**Comment by lk-geimfari** [comment]
@eumiro Seems like the only way is changing `end` to current every year.

**Comment by lk-geimfari** [comment]
I mean the only way without breaking things.

**Comment by lk-geimfari** [comment]
And we don't have to migrate to `calver`. We'll just mention such changes in CHANGELOG.

**Comment by lk-geimfari** [comment]
@eumiro Can you, please, check #872?

**Comment by lk-geimfari** [comment]
I think it will work with seed as well because date().year will always return the same value.

**Comment by eumiro** [comment]
It looks good. And it will return the same value within one year, which is probably okay for your users.
