### ISSUE TITLE
Add pricetag support

### ISSUE THREAD

**Issue by eumiro** [lk-geimfari/mimesis#871]
# Feature request
## Thesis

Create a localized pricetag:

```
>>> mimesis.Business().pricetag()
"$ 12.34"
>>> mimesis.Business("de").pricetag(minimum=1000, maximum=1500)
"1.234,56 €"
>>> mimesis.Business("cs").pricetag()
"75,20 Kč"        # rounded to 0.1
```
with defaults minimum=0.01 and maximum=1000.00 as a proposal for the default provider. Localized providers would define their own values, because of huge differences between the used values, such as USD/EUR/GBP going down to 0.01, and some minor currencies using millions as base.

## Reasoning

This is very locale dependent. Currency is already in the `CURRENCY_SYMBOLS`, but what would be the best place for localized number and price formatting as well as the localized defaults for minimum/maximum?

**Comment by lk-geimfari** [comment]
@eumiro I think this is a good idea. Any change you can work on it?

**Comment by lk-geimfari** [comment]
@eumiro We already have something similar there: `.price()`

**Comment by lk-geimfari** [comment]
It was a bad idea to return str from `.price()` of course.

**Comment by lk-geimfari** [comment]
<img width="439" alt="Screenshot 2020-06-06 at 13 02 18" src="https://user-images.githubusercontent.com/15812620/83941690-fbb52400-a7f5-11ea-933d-a00690727034.png">

**Comment by eumiro** [comment]
Yes, but it does not format numbers nor position the currency symbol according to the locale and the values go down to 0.01.

**Comment by lk-geimfari** [comment]
@eumiro We can just add such features to it. There is not necessary to duplicate almost the same features.

**Comment by lk-geimfari** [comment]
@eumiro If you're interested then you can create PR with changes.

**Comment by eumiro** [comment]
@lk-geimfari do you have any plans to include general locale formatting support for numbers etc.? I mean if `de` price format is one of `#,## €`, `##,## €`, `###,## €`,  `#.###,## €`, … and the `cs` one `#,#0 Kč`, `##,#0 Kč`, `###,#0 Kč`, `# ###,#0 Kč`, …  then I could put all of them into `mimesis/data/…/business.json` and then pick up one randomly, but if we want a random number between `minimum` and `maximum`, then we'll have to connect these formats to the selected value.

**Comment by lk-geimfari** [comment]
@eumiro Sure! Sounds good. You can define number formation for each locale in their `business.json`.
