### ISSUE TITLE
The matrix method fails sometimes

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#878]
# Bug report

Details: https://travis-ci.org/github/lk-geimfari/mimesis/jobs/696138838

**Comment by eumiro** [comment]
This happens for numbers like `(0.4889+6e-06j)`, i.e. when the real or imag part are too small and are converted to scientific notation.

**Comment by lk-geimfari** [comment]
@eumiro Any chance you can work on this?

**Comment by eumiro** [comment]
Fix provided, although I'd prefer to avoid `round` on floats altogether. I'd leave `float` as is (without precision), or use precise `decimal.Decimal`, or formatted `str` instead.
