### ISSUE TITLE
Add full localized formatted date provider

### ISSUE THREAD

**Issue by eumiro** [lk-geimfari/mimesis#882]
# Feature request
## Thesis

Add full localized formatted date provider, such as:

```
June 11, 2020
11. Juni 2020
11 juin 2020
11. júna 2020
11 de junho de 2020
11 июня 2020
```

## Reasoning

Now only numerical formats are possible (`Y-M-D`, `D.M.Y`, `D/M/Y`, `M/D/Y`) and the names of months (and of weekdays too) are available only as a random text unrelated to any date. Especially in the longer format, such as `Thursday, June 11, 2020` some consistency should be guaranteed, e.g. to test date parsers.

## TODOs:

- the order of entries in the localized `datetime.json` must be chronological and not alphabetical (or changed to a dict)
- new placeholders, such as `a`, `A`, `b`, and `B` must be added to the `formats` entries
- `formatted_date` accepts already a general `fmt`, which however uses default names, so e.g. `mimesis.Datetime("de").formatted_date("%A %d.%m.%Y")` returns `Thursday 11.06.2020` instead of `Donnerstag 11.06.2020`.

**Comment by lk-geimfari** [comment]
You can see related issues here: https://github.com/lk-geimfari/mimesis/issues/804

**Comment by lk-geimfari** [comment]
Have a look at this comment: https://github.com/lk-geimfari/mimesis/issues/804#issuecomment-578406680

**Comment by lk-geimfari** [comment]
Tst
