### ISSUE TITLE
Add PR labeler

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#891]
https://github.com/actions/labeler

We can use it to mark PRs related to each part of mimesis.

When changes related to the `docs` it will be `docs-change`, when it's `mimesis/data` it will be `data-change` etc.

**Comment by aekt** [comment]
Hi @lk-geimfari, can I help on this?

And for changes on `mimesis/*.py` files, what label is expected?

**Comment by lk-geimfari** [comment]
@aekt Sure you can! 

mimesis/data/ — `data-change`
mimesis/providers/*.py — `provider-changes`
docs/ — `documentation`
tests/ — `tests`
mimesis/*.py — no labels
