### ISSUE TITLE
PyCharm indicates wrong type for lambda

### ISSUE THREAD

**Issue by michael0liver** [lk-geimfari/mimesis#928]
# Bug report

## What's wrong

While using PyCharm,  `lambda` type in `Schema` results in *Expected type 'FunctionType', got '() -> Dict[str, Union[str, Any]]' instead*
![Screenshot 2020-08-28 at 07 59 37](https://user-images.githubusercontent.com/55017335/91531501-ca378a80-e904-11ea-9558-5b44bcff7040.png)

## How is that should be
Is this warning correct? The code runs perfectly fine but maybe the Type maybe be wrong here. On this [SO post](https://stackoverflow.com/a/33833896/12794150) they mentioned using the `from typing import Callable` for type hinting a lambda.

## System information

```
❯ python3 --version
Python 3.8.5

❯ sw_vers
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5354i
```
PyCharm 2020.2.1

**Comment by lk-geimfari** [comment]
I've noticed this behavior too. I think this happens since one of the last releases of `mypy`. I think that we can use `Callable`.

**Comment by lk-geimfari** [comment]
If you have free time then you can create a PR, of course.

**Comment by michael0liver** [comment]
Sorry I didn't get time, I see you have started now :)
Maybe next time !
