### ISSUE TITLE
Add vn (vietnamese) language

### ISSUE THREAD

**Issue by dinhanhx** [lk-geimfari/mimesis#950]
# Feature request

Add vn folder to data folder

## Thesis

I will use ~/mimeis/data/en as base to make a version for vn language

## Reasoning

- I am Vietnamese

- I want to do something for hackotber2020 and for my people

**Comment by lk-geimfari** [comment]
I don't mind, but only if you can guarantee the completeness and the volume of data. Collecting enough data is a time-consuming task, so if you are not sure that you will complete this task, then it is better not to waste your time and mine.

**Comment by lk-geimfari** [comment]
If you are serious about the contribution to this project and ready to spend time on this, then have a look: [CONTRIBUTING](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)

**Comment by dinhanhx** [comment]
Sorry for bothering you. I find out that if I do this under 23 days, I will be overwhelmed with other school works. I will close this issue.

**Comment by lk-geimfari** [comment]
@dinhanhx It's okay!
