### ISSUE TITLE
Russian locale is unreasonably big

### ISSUE THREAD

**Issue by alexanderfefelov** [lk-geimfari/mimesis#971]
[person.json](https://github.com/lk-geimfari/mimesis/blob/master/mimesis/data/ru/person.json) for russian locale is oversized. Compare his 158 klines with 6 klines in [english version](https://github.com/lk-geimfari/mimesis/blob/master/mimesis/data/en/person.json). The dictionaries contains a ton of crap like"Абдулгаллямов",   "Некрут", "Прибыток", "Хач", "Шт" etc, impacts performance/memory.

Rapid benchmarking

```python
#!/usr/bin/env python3


from mimesis import Person
import time

def run_test(locale, n):
    start_time = time.time()
    gen = Person(locale)
    for i in range(0, n):
        _ = gen.last_name()
    end_time = time.time()
    print('%s: %d operations, %f seconds' % (locale, n, end_time - start_time))

N = 1000000
run_test('ru', N)
run_test('en', N)
```

shows such results

```
ru: 1000000 operations, 8.939918 seconds
en: 1000000 operations, 1.817508 seconds
```

Dictionaries need to be washed.

**Comment by lk-geimfari** [comment]
Yeah, the names and surnames should be updated for sure. This data was collected from the open resources and they weren't checked.
