### ISSUE TITLE
Remove Travis CI completely.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#976]
After checking Github Actions, Travis CI should be removed completely.

**Comment by eumiro** [comment]
Is this finished? In a new PR, such as #981, following line appears: `continuous-integration/travis-ci Expected — Waiting for status to be reported` and there's even a report email coming from travis.

**Comment by lk-geimfari** [comment]
@eumiro Actually it should be, but I see that it's not. I'm gonna fix this one.

**Comment by lk-geimfari** [comment]
@eumiro It's pretty strange because I've removed all applications and integrations from this repository.

**Comment by lk-geimfari** [comment]
It's done now.

**Comment by lk-geimfari** [comment]
I'm closing this. Thank you very much for your help, @michael0liver!
