### ISSUE TITLE
Show result of test action for all pull requests.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#982]
Right now we can see the result of changes only after merging PR to the master branch. It's good to see the result of the test right on PR's page.

**Comment by lk-geimfari** [comment]
@michael0liver Since initially Github Actions was added by you, maybe this one will be interesting for you too? Thank you!

**Comment by michael0liver** [comment]
Hey @lk-geimfari I got a notification that you tagged me but I can't see the message?
